// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/admin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminEmpty) Reset() {
	*x = AdminEmpty{}
	mi := &file_proto_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminEmpty) ProtoMessage() {}

func (x *AdminEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminEmpty.ProtoReflect.Descriptor instead.
func (*AdminEmpty) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{0}
}

type AdminUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Role          int32                  `protobuf:"varint,5,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUser) Reset() {
	*x = AdminUser{}
	mi := &file_proto_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUser) ProtoMessage() {}

func (x *AdminUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUser.ProtoReflect.Descriptor instead.
func (*AdminUser) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AdminUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AdminUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminUser) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AdminUser) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *AdminUser) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *AdminUser) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AdminLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	UserAgent     string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLoginRequest) Reset() {
	*x = AdminLoginRequest{}
	mi := &file_proto_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginRequest) ProtoMessage() {}

func (x *AdminLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginRequest.ProtoReflect.Descriptor instead.
func (*AdminLoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{2}
}

func (x *AdminLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AdminLoginRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *AdminLoginRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type AdminLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	User          *AdminUser             `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLoginResponse) Reset() {
	*x = AdminLoginResponse{}
	mi := &file_proto_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginResponse) ProtoMessage() {}

func (x *AdminLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginResponse.ProtoReflect.Descriptor instead.
func (*AdminLoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{3}
}

func (x *AdminLoginResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AdminLoginResponse) GetUser() *AdminUser {
	if x != nil {
		return x.User
	}
	return nil
}

type AdminLogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLogoutRequest) Reset() {
	*x = AdminLogoutRequest{}
	mi := &file_proto_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLogoutRequest) ProtoMessage() {}

func (x *AdminLogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLogoutRequest.ProtoReflect.Descriptor instead.
func (*AdminLogoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{4}
}

func (x *AdminLogoutRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AdminSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminSessionRequest) Reset() {
	*x = AdminSessionRequest{}
	mi := &file_proto_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSessionRequest) ProtoMessage() {}

func (x *AdminSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSessionRequest.ProtoReflect.Descriptor instead.
func (*AdminSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{5}
}

func (x *AdminSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AdminCurrentUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *AdminUser             `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminCurrentUserResponse) Reset() {
	*x = AdminCurrentUserResponse{}
	mi := &file_proto_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminCurrentUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCurrentUserResponse) ProtoMessage() {}

func (x *AdminCurrentUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCurrentUserResponse.ProtoReflect.Descriptor instead.
func (*AdminCurrentUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{6}
}

func (x *AdminCurrentUserResponse) GetUser() *AdminUser {
	if x != nil {
		return x.User
	}
	return nil
}

type AdminOverviewResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalUsers          int64                  `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	DailyActiveUsers    int64                  `protobuf:"varint,2,opt,name=daily_active_users,json=dailyActiveUsers,proto3" json:"daily_active_users,omitempty"`
	WeeklyActiveUsers   int64                  `protobuf:"varint,3,opt,name=weekly_active_users,json=weeklyActiveUsers,proto3" json:"weekly_active_users,omitempty"`
	TotalDownloads      int64                  `protobuf:"varint,4,opt,name=total_downloads,json=totalDownloads,proto3" json:"total_downloads,omitempty"`
	DownloadsToday      int64                  `protobuf:"varint,5,opt,name=downloads_today,json=downloadsToday,proto3" json:"downloads_today,omitempty"`
	SuccessDownloads    int64                  `protobuf:"varint,6,opt,name=success_downloads,json=successDownloads,proto3" json:"success_downloads,omitempty"`
	FailedDownloads     int64                  `protobuf:"varint,7,opt,name=failed_downloads,json=failedDownloads,proto3" json:"failed_downloads,omitempty"`
	ActiveManualProxies int64                  `protobuf:"varint,8,opt,name=active_manual_proxies,json=activeManualProxies,proto3" json:"active_manual_proxies,omitempty"`
	TotalManualProxies  int64                  `protobuf:"varint,9,opt,name=total_manual_proxies,json=totalManualProxies,proto3" json:"total_manual_proxies,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AdminOverviewResponse) Reset() {
	*x = AdminOverviewResponse{}
	mi := &file_proto_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminOverviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminOverviewResponse) ProtoMessage() {}

func (x *AdminOverviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminOverviewResponse.ProtoReflect.Descriptor instead.
func (*AdminOverviewResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{7}
}

func (x *AdminOverviewResponse) GetTotalUsers() int64 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *AdminOverviewResponse) GetDailyActiveUsers() int64 {
	if x != nil {
		return x.DailyActiveUsers
	}
	return 0
}

func (x *AdminOverviewResponse) GetWeeklyActiveUsers() int64 {
	if x != nil {
		return x.WeeklyActiveUsers
	}
	return 0
}

func (x *AdminOverviewResponse) GetTotalDownloads() int64 {
	if x != nil {
		return x.TotalDownloads
	}
	return 0
}

func (x *AdminOverviewResponse) GetDownloadsToday() int64 {
	if x != nil {
		return x.DownloadsToday
	}
	return 0
}

func (x *AdminOverviewResponse) GetSuccessDownloads() int64 {
	if x != nil {
		return x.SuccessDownloads
	}
	return 0
}

func (x *AdminOverviewResponse) GetFailedDownloads() int64 {
	if x != nil {
		return x.FailedDownloads
	}
	return 0
}

func (x *AdminOverviewResponse) GetActiveManualProxies() int64 {
	if x != nil {
		return x.ActiveManualProxies
	}
	return 0
}

func (x *AdminOverviewResponse) GetTotalManualProxies() int64 {
	if x != nil {
		return x.TotalManualProxies
	}
	return 0
}

type AdminTrendPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminTrendPoint) Reset() {
	*x = AdminTrendPoint{}
	mi := &file_proto_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminTrendPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminTrendPoint) ProtoMessage() {}

func (x *AdminTrendPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminTrendPoint.ProtoReflect.Descriptor instead.
func (*AdminTrendPoint) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{8}
}

func (x *AdminTrendPoint) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AdminTrendPoint) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AdminRequestTrendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Granularity   string                 `protobuf:"bytes,1,opt,name=granularity,proto3" json:"granularity,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRequestTrendRequest) Reset() {
	*x = AdminRequestTrendRequest{}
	mi := &file_proto_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRequestTrendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRequestTrendRequest) ProtoMessage() {}

func (x *AdminRequestTrendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRequestTrendRequest.ProtoReflect.Descriptor instead.
func (*AdminRequestTrendRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{9}
}

func (x *AdminRequestTrendRequest) GetGranularity() string {
	if x != nil {
		return x.Granularity
	}
	return ""
}

func (x *AdminRequestTrendRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AdminRequestTrendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Granularity   string                 `protobuf:"bytes,1,opt,name=granularity,proto3" json:"granularity,omitempty"`
	Points        []*AdminTrendPoint     `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRequestTrendResponse) Reset() {
	*x = AdminRequestTrendResponse{}
	mi := &file_proto_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRequestTrendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRequestTrendResponse) ProtoMessage() {}

func (x *AdminRequestTrendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRequestTrendResponse.ProtoReflect.Descriptor instead.
func (*AdminRequestTrendResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{10}
}

func (x *AdminRequestTrendResponse) GetGranularity() string {
	if x != nil {
		return x.Granularity
	}
	return ""
}

func (x *AdminRequestTrendResponse) GetPoints() []*AdminTrendPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type AdminUserStatsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalUsers        int64                  `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	DailyActiveUsers  int64                  `protobuf:"varint,2,opt,name=daily_active_users,json=dailyActiveUsers,proto3" json:"daily_active_users,omitempty"`
	WeeklyActiveUsers int64                  `protobuf:"varint,3,opt,name=weekly_active_users,json=weeklyActiveUsers,proto3" json:"weekly_active_users,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AdminUserStatsResponse) Reset() {
	*x = AdminUserStatsResponse{}
	mi := &file_proto_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserStatsResponse) ProtoMessage() {}

func (x *AdminUserStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserStatsResponse.ProtoReflect.Descriptor instead.
func (*AdminUserStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{11}
}

func (x *AdminUserStatsResponse) GetTotalUsers() int64 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *AdminUserStatsResponse) GetDailyActiveUsers() int64 {
	if x != nil {
		return x.DailyActiveUsers
	}
	return 0
}

func (x *AdminUserStatsResponse) GetWeeklyActiveUsers() int64 {
	if x != nil {
		return x.WeeklyActiveUsers
	}
	return 0
}

type AdminProxySourceStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ProxyUrl      string                 `protobuf:"bytes,4,opt,name=proxy_url,json=proxyUrl,proto3" json:"proxy_url,omitempty"`
	ProxyLeaseId  string                 `protobuf:"bytes,5,opt,name=proxy_lease_id,json=proxyLeaseId,proto3" json:"proxy_lease_id,omitempty"`
	ProxyExpireAt string                 `protobuf:"bytes,6,opt,name=proxy_expire_at,json=proxyExpireAt,proto3" json:"proxy_expire_at,omitempty"`
	CheckedAt     string                 `protobuf:"bytes,7,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminProxySourceStatusResponse) Reset() {
	*x = AdminProxySourceStatusResponse{}
	mi := &file_proto_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminProxySourceStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminProxySourceStatusResponse) ProtoMessage() {}

func (x *AdminProxySourceStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminProxySourceStatusResponse.ProtoReflect.Descriptor instead.
func (*AdminProxySourceStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{12}
}

func (x *AdminProxySourceStatusResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *AdminProxySourceStatusResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *AdminProxySourceStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AdminProxySourceStatusResponse) GetProxyUrl() string {
	if x != nil {
		return x.ProxyUrl
	}
	return ""
}

func (x *AdminProxySourceStatusResponse) GetProxyLeaseId() string {
	if x != nil {
		return x.ProxyLeaseId
	}
	return ""
}

func (x *AdminProxySourceStatusResponse) GetProxyExpireAt() string {
	if x != nil {
		return x.ProxyExpireAt
	}
	return ""
}

func (x *AdminProxySourceStatusResponse) GetCheckedAt() string {
	if x != nil {
		return x.CheckedAt
	}
	return ""
}

type AdminProxySourcePolicyResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Id                       int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ScopeType                string                 `protobuf:"bytes,2,opt,name=scope_type,json=scopeType,proto3" json:"scope_type,omitempty"`
	ScopeValue               string                 `protobuf:"bytes,3,opt,name=scope_value,json=scopeValue,proto3" json:"scope_value,omitempty"`
	PrimarySource            string                 `protobuf:"bytes,4,opt,name=primary_source,json=primarySource,proto3" json:"primary_source,omitempty"`
	FallbackSource           string                 `protobuf:"bytes,5,opt,name=fallback_source,json=fallbackSource,proto3" json:"fallback_source,omitempty"`
	FallbackEnabled          bool                   `protobuf:"varint,6,opt,name=fallback_enabled,json=fallbackEnabled,proto3" json:"fallback_enabled,omitempty"`
	DynamicTimeoutMs         int32                  `protobuf:"varint,7,opt,name=dynamic_timeout_ms,json=dynamicTimeoutMs,proto3" json:"dynamic_timeout_ms,omitempty"`
	DynamicRetryCount        int32                  `protobuf:"varint,8,opt,name=dynamic_retry_count,json=dynamicRetryCount,proto3" json:"dynamic_retry_count,omitempty"`
	DynamicCircuitBreakerSec int32                  `protobuf:"varint,9,opt,name=dynamic_circuit_breaker_sec,json=dynamicCircuitBreakerSec,proto3" json:"dynamic_circuit_breaker_sec,omitempty"`
	MinLeaseTtlSec           int32                  `protobuf:"varint,10,opt,name=min_lease_ttl_sec,json=minLeaseTtlSec,proto3" json:"min_lease_ttl_sec,omitempty"`
	ManualSelectionStrategy  string                 `protobuf:"bytes,11,opt,name=manual_selection_strategy,json=manualSelectionStrategy,proto3" json:"manual_selection_strategy,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AdminProxySourcePolicyResponse) Reset() {
	*x = AdminProxySourcePolicyResponse{}
	mi := &file_proto_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminProxySourcePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminProxySourcePolicyResponse) ProtoMessage() {}

func (x *AdminProxySourcePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminProxySourcePolicyResponse.ProtoReflect.Descriptor instead.
func (*AdminProxySourcePolicyResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{13}
}

func (x *AdminProxySourcePolicyResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminProxySourcePolicyResponse) GetScopeType() string {
	if x != nil {
		return x.ScopeType
	}
	return ""
}

func (x *AdminProxySourcePolicyResponse) GetScopeValue() string {
	if x != nil {
		return x.ScopeValue
	}
	return ""
}

func (x *AdminProxySourcePolicyResponse) GetPrimarySource() string {
	if x != nil {
		return x.PrimarySource
	}
	return ""
}

func (x *AdminProxySourcePolicyResponse) GetFallbackSource() string {
	if x != nil {
		return x.FallbackSource
	}
	return ""
}

func (x *AdminProxySourcePolicyResponse) GetFallbackEnabled() bool {
	if x != nil {
		return x.FallbackEnabled
	}
	return false
}

func (x *AdminProxySourcePolicyResponse) GetDynamicTimeoutMs() int32 {
	if x != nil {
		return x.DynamicTimeoutMs
	}
	return 0
}

func (x *AdminProxySourcePolicyResponse) GetDynamicRetryCount() int32 {
	if x != nil {
		return x.DynamicRetryCount
	}
	return 0
}

func (x *AdminProxySourcePolicyResponse) GetDynamicCircuitBreakerSec() int32 {
	if x != nil {
		return x.DynamicCircuitBreakerSec
	}
	return 0
}

func (x *AdminProxySourcePolicyResponse) GetMinLeaseTtlSec() int32 {
	if x != nil {
		return x.MinLeaseTtlSec
	}
	return 0
}

func (x *AdminProxySourcePolicyResponse) GetManualSelectionStrategy() string {
	if x != nil {
		return x.ManualSelectionStrategy
	}
	return ""
}

type AdminUpdateProxySourcePolicyRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Id                       int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PrimarySource            string                 `protobuf:"bytes,2,opt,name=primary_source,json=primarySource,proto3" json:"primary_source,omitempty"`
	FallbackSource           string                 `protobuf:"bytes,3,opt,name=fallback_source,json=fallbackSource,proto3" json:"fallback_source,omitempty"`
	FallbackEnabled          bool                   `protobuf:"varint,4,opt,name=fallback_enabled,json=fallbackEnabled,proto3" json:"fallback_enabled,omitempty"`
	DynamicTimeoutMs         int32                  `protobuf:"varint,5,opt,name=dynamic_timeout_ms,json=dynamicTimeoutMs,proto3" json:"dynamic_timeout_ms,omitempty"`
	DynamicRetryCount        int32                  `protobuf:"varint,6,opt,name=dynamic_retry_count,json=dynamicRetryCount,proto3" json:"dynamic_retry_count,omitempty"`
	DynamicCircuitBreakerSec int32                  `protobuf:"varint,7,opt,name=dynamic_circuit_breaker_sec,json=dynamicCircuitBreakerSec,proto3" json:"dynamic_circuit_breaker_sec,omitempty"`
	MinLeaseTtlSec           int32                  `protobuf:"varint,8,opt,name=min_lease_ttl_sec,json=minLeaseTtlSec,proto3" json:"min_lease_ttl_sec,omitempty"`
	ManualSelectionStrategy  string                 `protobuf:"bytes,9,opt,name=manual_selection_strategy,json=manualSelectionStrategy,proto3" json:"manual_selection_strategy,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AdminUpdateProxySourcePolicyRequest) Reset() {
	*x = AdminUpdateProxySourcePolicyRequest{}
	mi := &file_proto_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateProxySourcePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateProxySourcePolicyRequest) ProtoMessage() {}

func (x *AdminUpdateProxySourcePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateProxySourcePolicyRequest.ProtoReflect.Descriptor instead.
func (*AdminUpdateProxySourcePolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{14}
}

func (x *AdminUpdateProxySourcePolicyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUpdateProxySourcePolicyRequest) GetPrimarySource() string {
	if x != nil {
		return x.PrimarySource
	}
	return ""
}

func (x *AdminUpdateProxySourcePolicyRequest) GetFallbackSource() string {
	if x != nil {
		return x.FallbackSource
	}
	return ""
}

func (x *AdminUpdateProxySourcePolicyRequest) GetFallbackEnabled() bool {
	if x != nil {
		return x.FallbackEnabled
	}
	return false
}

func (x *AdminUpdateProxySourcePolicyRequest) GetDynamicTimeoutMs() int32 {
	if x != nil {
		return x.DynamicTimeoutMs
	}
	return 0
}

func (x *AdminUpdateProxySourcePolicyRequest) GetDynamicRetryCount() int32 {
	if x != nil {
		return x.DynamicRetryCount
	}
	return 0
}

func (x *AdminUpdateProxySourcePolicyRequest) GetDynamicCircuitBreakerSec() int32 {
	if x != nil {
		return x.DynamicCircuitBreakerSec
	}
	return 0
}

func (x *AdminUpdateProxySourcePolicyRequest) GetMinLeaseTtlSec() int32 {
	if x != nil {
		return x.MinLeaseTtlSec
	}
	return 0
}

func (x *AdminUpdateProxySourcePolicyRequest) GetManualSelectionStrategy() string {
	if x != nil {
		return x.ManualSelectionStrategy
	}
	return ""
}

type AdminProxyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Region        string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	PlatformTags  string                 `protobuf:"bytes,8,opt,name=platform_tags,json=platformTags,proto3" json:"platform_tags,omitempty"`
	Remark        string                 `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	LastUsedAt    string                 `protobuf:"bytes,11,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	SuccessCount  int32                  `protobuf:"varint,12,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailCount     int32                  `protobuf:"varint,13,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminProxyInfo) Reset() {
	*x = AdminProxyInfo{}
	mi := &file_proto_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminProxyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminProxyInfo) ProtoMessage() {}

func (x *AdminProxyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminProxyInfo.ProtoReflect.Descriptor instead.
func (*AdminProxyInfo) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{15}
}

func (x *AdminProxyInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminProxyInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *AdminProxyInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AdminProxyInfo) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *AdminProxyInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminProxyInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AdminProxyInfo) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *AdminProxyInfo) GetPlatformTags() string {
	if x != nil {
		return x.PlatformTags
	}
	return ""
}

func (x *AdminProxyInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *AdminProxyInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AdminProxyInfo) GetLastUsedAt() string {
	if x != nil {
		return x.LastUsedAt
	}
	return ""
}

func (x *AdminProxyInfo) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *AdminProxyInfo) GetFailCount() int32 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

func (x *AdminProxyInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AdminProxyInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type AdminListProxiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	HasStatus     bool                   `protobuf:"varint,5,opt,name=has_status,json=hasStatus,proto3" json:"has_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListProxiesRequest) Reset() {
	*x = AdminListProxiesRequest{}
	mi := &file_proto_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListProxiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListProxiesRequest) ProtoMessage() {}

func (x *AdminListProxiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListProxiesRequest.ProtoReflect.Descriptor instead.
func (*AdminListProxiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{16}
}

func (x *AdminListProxiesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *AdminListProxiesRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *AdminListProxiesRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AdminListProxiesRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AdminListProxiesRequest) GetHasStatus() bool {
	if x != nil {
		return x.HasStatus
	}
	return false
}

type AdminListProxiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AdminProxyInfo      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListProxiesResponse) Reset() {
	*x = AdminListProxiesResponse{}
	mi := &file_proto_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListProxiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListProxiesResponse) ProtoMessage() {}

func (x *AdminListProxiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListProxiesResponse.ProtoReflect.Descriptor instead.
func (*AdminListProxiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{17}
}

func (x *AdminListProxiesResponse) GetItems() []*AdminProxyInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type AdminCreateProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Region        string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	PlatformTags  string                 `protobuf:"bytes,8,opt,name=platform_tags,json=platformTags,proto3" json:"platform_tags,omitempty"`
	Remark        string                 `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminCreateProxyRequest) Reset() {
	*x = AdminCreateProxyRequest{}
	mi := &file_proto_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminCreateProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCreateProxyRequest) ProtoMessage() {}

func (x *AdminCreateProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCreateProxyRequest.ProtoReflect.Descriptor instead.
func (*AdminCreateProxyRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{18}
}

func (x *AdminCreateProxyRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *AdminCreateProxyRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AdminCreateProxyRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *AdminCreateProxyRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminCreateProxyRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AdminCreateProxyRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AdminCreateProxyRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *AdminCreateProxyRequest) GetPlatformTags() string {
	if x != nil {
		return x.PlatformTags
	}
	return ""
}

func (x *AdminCreateProxyRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *AdminCreateProxyRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AdminUpdateProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Region        string                 `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`
	Priority      int32                  `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	PlatformTags  string                 `protobuf:"bytes,9,opt,name=platform_tags,json=platformTags,proto3" json:"platform_tags,omitempty"`
	Remark        string                 `protobuf:"bytes,10,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdateProxyRequest) Reset() {
	*x = AdminUpdateProxyRequest{}
	mi := &file_proto_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateProxyRequest) ProtoMessage() {}

func (x *AdminUpdateProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateProxyRequest.ProtoReflect.Descriptor instead.
func (*AdminUpdateProxyRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{19}
}

func (x *AdminUpdateProxyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUpdateProxyRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *AdminUpdateProxyRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AdminUpdateProxyRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *AdminUpdateProxyRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminUpdateProxyRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AdminUpdateProxyRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AdminUpdateProxyRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *AdminUpdateProxyRequest) GetPlatformTags() string {
	if x != nil {
		return x.PlatformTags
	}
	return ""
}

func (x *AdminUpdateProxyRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type AdminUpdateProxyStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdateProxyStatusRequest) Reset() {
	*x = AdminUpdateProxyStatusRequest{}
	mi := &file_proto_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateProxyStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateProxyStatusRequest) ProtoMessage() {}

func (x *AdminUpdateProxyStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateProxyStatusRequest.ProtoReflect.Descriptor instead.
func (*AdminUpdateProxyStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{20}
}

func (x *AdminUpdateProxyStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUpdateProxyStatusRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AdminDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteRequest) Reset() {
	*x = AdminDeleteRequest{}
	mi := &file_proto_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteRequest) ProtoMessage() {}

func (x *AdminDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteRequest.ProtoReflect.Descriptor instead.
func (*AdminDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{21}
}

func (x *AdminDeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AdminCookieInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	ExpireAt      string                 `protobuf:"bytes,6,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	FrozenUntil   string                 `protobuf:"bytes,7,opt,name=frozen_until,json=frozenUntil,proto3" json:"frozen_until,omitempty"`
	FreezeSeconds int32                  `protobuf:"varint,8,opt,name=freeze_seconds,json=freezeSeconds,proto3" json:"freeze_seconds,omitempty"`
	LastUsedAt    string                 `protobuf:"bytes,9,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	UseCount      int64                  `protobuf:"varint,10,opt,name=use_count,json=useCount,proto3" json:"use_count,omitempty"`
	SuccessCount  int64                  `protobuf:"varint,11,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailCount     int64                  `protobuf:"varint,12,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminCookieInfo) Reset() {
	*x = AdminCookieInfo{}
	mi := &file_proto_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminCookieInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCookieInfo) ProtoMessage() {}

func (x *AdminCookieInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCookieInfo.ProtoReflect.Descriptor instead.
func (*AdminCookieInfo) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{22}
}

func (x *AdminCookieInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminCookieInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AdminCookieInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminCookieInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AdminCookieInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AdminCookieInfo) GetExpireAt() string {
	if x != nil {
		return x.ExpireAt
	}
	return ""
}

func (x *AdminCookieInfo) GetFrozenUntil() string {
	if x != nil {
		return x.FrozenUntil
	}
	return ""
}

func (x *AdminCookieInfo) GetFreezeSeconds() int32 {
	if x != nil {
		return x.FreezeSeconds
	}
	return 0
}

func (x *AdminCookieInfo) GetLastUsedAt() string {
	if x != nil {
		return x.LastUsedAt
	}
	return ""
}

func (x *AdminCookieInfo) GetUseCount() int64 {
	if x != nil {
		return x.UseCount
	}
	return 0
}

func (x *AdminCookieInfo) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *AdminCookieInfo) GetFailCount() int64 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

func (x *AdminCookieInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AdminCookieInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type AdminListCookiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListCookiesRequest) Reset() {
	*x = AdminListCookiesRequest{}
	mi := &file_proto_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListCookiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListCookiesRequest) ProtoMessage() {}

func (x *AdminListCookiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListCookiesRequest.ProtoReflect.Descriptor instead.
func (*AdminListCookiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{23}
}

func (x *AdminListCookiesRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AdminListCookiesRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AdminListCookiesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AdminListCookiesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type AdminListCookiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Items         []*AdminCookieInfo     `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListCookiesResponse) Reset() {
	*x = AdminListCookiesResponse{}
	mi := &file_proto_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListCookiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListCookiesResponse) ProtoMessage() {}

func (x *AdminListCookiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListCookiesResponse.ProtoReflect.Descriptor instead.
func (*AdminListCookiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{24}
}

func (x *AdminListCookiesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AdminListCookiesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AdminListCookiesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AdminListCookiesResponse) GetItems() []*AdminCookieInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type AdminGetCookieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetCookieRequest) Reset() {
	*x = AdminGetCookieRequest{}
	mi := &file_proto_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetCookieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetCookieRequest) ProtoMessage() {}

func (x *AdminGetCookieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetCookieRequest.ProtoReflect.Descriptor instead.
func (*AdminGetCookieRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{25}
}

func (x *AdminGetCookieRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AdminGetCookieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cookie        *AdminCookieInfo       `protobuf:"bytes,1,opt,name=cookie,proto3" json:"cookie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetCookieResponse) Reset() {
	*x = AdminGetCookieResponse{}
	mi := &file_proto_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetCookieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetCookieResponse) ProtoMessage() {}

func (x *AdminGetCookieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetCookieResponse.ProtoReflect.Descriptor instead.
func (*AdminGetCookieResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{26}
}

func (x *AdminGetCookieResponse) GetCookie() *AdminCookieInfo {
	if x != nil {
		return x.Cookie
	}
	return nil
}

type AdminCreateCookieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ExpireAt      string                 `protobuf:"bytes,4,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	FreezeSeconds int32                  `protobuf:"varint,5,opt,name=freeze_seconds,json=freezeSeconds,proto3" json:"freeze_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminCreateCookieRequest) Reset() {
	*x = AdminCreateCookieRequest{}
	mi := &file_proto_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminCreateCookieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCreateCookieRequest) ProtoMessage() {}

func (x *AdminCreateCookieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCreateCookieRequest.ProtoReflect.Descriptor instead.
func (*AdminCreateCookieRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{27}
}

func (x *AdminCreateCookieRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AdminCreateCookieRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminCreateCookieRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AdminCreateCookieRequest) GetExpireAt() string {
	if x != nil {
		return x.ExpireAt
	}
	return ""
}

func (x *AdminCreateCookieRequest) GetFreezeSeconds() int32 {
	if x != nil {
		return x.FreezeSeconds
	}
	return 0
}

type AdminUpdateCookieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ExpireAt      string                 `protobuf:"bytes,4,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	FreezeSeconds int32                  `protobuf:"varint,5,opt,name=freeze_seconds,json=freezeSeconds,proto3" json:"freeze_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdateCookieRequest) Reset() {
	*x = AdminUpdateCookieRequest{}
	mi := &file_proto_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateCookieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateCookieRequest) ProtoMessage() {}

func (x *AdminUpdateCookieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateCookieRequest.ProtoReflect.Descriptor instead.
func (*AdminUpdateCookieRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{28}
}

func (x *AdminUpdateCookieRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUpdateCookieRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminUpdateCookieRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AdminUpdateCookieRequest) GetExpireAt() string {
	if x != nil {
		return x.ExpireAt
	}
	return ""
}

func (x *AdminUpdateCookieRequest) GetFreezeSeconds() int32 {
	if x != nil {
		return x.FreezeSeconds
	}
	return 0
}

type AdminFreezeCookieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FreezeSeconds int32                  `protobuf:"varint,2,opt,name=freeze_seconds,json=freezeSeconds,proto3" json:"freeze_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminFreezeCookieRequest) Reset() {
	*x = AdminFreezeCookieRequest{}
	mi := &file_proto_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFreezeCookieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFreezeCookieRequest) ProtoMessage() {}

func (x *AdminFreezeCookieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFreezeCookieRequest.ProtoReflect.Descriptor instead.
func (*AdminFreezeCookieRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{29}
}

func (x *AdminFreezeCookieRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminFreezeCookieRequest) GetFreezeSeconds() int32 {
	if x != nil {
		return x.FreezeSeconds
	}
	return 0
}

type AdminFreezeCookieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	FrozenUntil   string                 `protobuf:"bytes,2,opt,name=frozen_until,json=frozenUntil,proto3" json:"frozen_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminFreezeCookieResponse) Reset() {
	*x = AdminFreezeCookieResponse{}
	mi := &file_proto_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFreezeCookieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFreezeCookieResponse) ProtoMessage() {}

func (x *AdminFreezeCookieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFreezeCookieResponse.ProtoReflect.Descriptor instead.
func (*AdminFreezeCookieResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{30}
}

func (x *AdminFreezeCookieResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AdminFreezeCookieResponse) GetFrozenUntil() string {
	if x != nil {
		return x.FrozenUntil
	}
	return ""
}

type AdminCreateResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminCreateResourceResponse) Reset() {
	*x = AdminCreateResourceResponse{}
	mi := &file_proto_admin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminCreateResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCreateResourceResponse) ProtoMessage() {}

func (x *AdminCreateResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCreateResourceResponse.ProtoReflect.Descriptor instead.
func (*AdminCreateResourceResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{31}
}

func (x *AdminCreateResourceResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AdminOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminOperationResponse) Reset() {
	*x = AdminOperationResponse{}
	mi := &file_proto_admin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminOperationResponse) ProtoMessage() {}

func (x *AdminOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminOperationResponse.ProtoReflect.Descriptor instead.
func (*AdminOperationResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{32}
}

func (x *AdminOperationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_admin_proto protoreflect.FileDescriptor

const file_proto_admin_proto_rawDesc = "" +
	"\n" +
	"\x11proto/admin.proto\x12\x05admin\"\f\n" +
	"\n" +
	"AdminEmpty\"\xa8\x01\n" +
	"\tAdminUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x12\n" +
	"\x04role\x18\x05 \x01(\x05R\x04role\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\x83\x01\n" +
	"\x11AdminLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\"Y\n" +
	"\x12AdminLoginResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12$\n" +
	"\x04user\x18\x02 \x01(\v2\x10.admin.AdminUserR\x04user\"3\n" +
	"\x12AdminLogoutRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"4\n" +
	"\x13AdminSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"@\n" +
	"\x18AdminCurrentUserResponse\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.admin.AdminUserR\x04user\"\xa6\x03\n" +
	"\x15AdminOverviewResponse\x12\x1f\n" +
	"\vtotal_users\x18\x01 \x01(\x03R\n" +
	"totalUsers\x12,\n" +
	"\x12daily_active_users\x18\x02 \x01(\x03R\x10dailyActiveUsers\x12.\n" +
	"\x13weekly_active_users\x18\x03 \x01(\x03R\x11weeklyActiveUsers\x12'\n" +
	"\x0ftotal_downloads\x18\x04 \x01(\x03R\x0etotalDownloads\x12'\n" +
	"\x0fdownloads_today\x18\x05 \x01(\x03R\x0edownloadsToday\x12+\n" +
	"\x11success_downloads\x18\x06 \x01(\x03R\x10successDownloads\x12)\n" +
	"\x10failed_downloads\x18\a \x01(\x03R\x0ffailedDownloads\x122\n" +
	"\x15active_manual_proxies\x18\b \x01(\x03R\x13activeManualProxies\x120\n" +
	"\x14total_manual_proxies\x18\t \x01(\x03R\x12totalManualProxies\"=\n" +
	"\x0fAdminTrendPoint\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"R\n" +
	"\x18AdminRequestTrendRequest\x12 \n" +
	"\vgranularity\x18\x01 \x01(\tR\vgranularity\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"m\n" +
	"\x19AdminRequestTrendResponse\x12 \n" +
	"\vgranularity\x18\x01 \x01(\tR\vgranularity\x12.\n" +
	"\x06points\x18\x02 \x03(\v2\x16.admin.AdminTrendPointR\x06points\"\x97\x01\n" +
	"\x16AdminUserStatsResponse\x12\x1f\n" +
	"\vtotal_users\x18\x01 \x01(\x03R\n" +
	"totalUsers\x12,\n" +
	"\x12daily_active_users\x18\x02 \x01(\x03R\x10dailyActiveUsers\x12.\n" +
	"\x13weekly_active_users\x18\x03 \x01(\x03R\x11weeklyActiveUsers\"\xf2\x01\n" +
	"\x1eAdminProxySourceStatusResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1b\n" +
	"\tproxy_url\x18\x04 \x01(\tR\bproxyUrl\x12$\n" +
	"\x0eproxy_lease_id\x18\x05 \x01(\tR\fproxyLeaseId\x12&\n" +
	"\x0fproxy_expire_at\x18\x06 \x01(\tR\rproxyExpireAt\x12\x1d\n" +
	"\n" +
	"checked_at\x18\a \x01(\tR\tcheckedAt\"\xef\x03\n" +
	"\x1eAdminProxySourcePolicyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"scope_type\x18\x02 \x01(\tR\tscopeType\x12\x1f\n" +
	"\vscope_value\x18\x03 \x01(\tR\n" +
	"scopeValue\x12%\n" +
	"\x0eprimary_source\x18\x04 \x01(\tR\rprimarySource\x12'\n" +
	"\x0ffallback_source\x18\x05 \x01(\tR\x0efallbackSource\x12)\n" +
	"\x10fallback_enabled\x18\x06 \x01(\bR\x0ffallbackEnabled\x12,\n" +
	"\x12dynamic_timeout_ms\x18\a \x01(\x05R\x10dynamicTimeoutMs\x12.\n" +
	"\x13dynamic_retry_count\x18\b \x01(\x05R\x11dynamicRetryCount\x12=\n" +
	"\x1bdynamic_circuit_breaker_sec\x18\t \x01(\x05R\x18dynamicCircuitBreakerSec\x12)\n" +
	"\x11min_lease_ttl_sec\x18\n" +
	" \x01(\x05R\x0eminLeaseTtlSec\x12:\n" +
	"\x19manual_selection_strategy\x18\v \x01(\tR\x17manualSelectionStrategy\"\xb4\x03\n" +
	"#AdminUpdateProxySourcePolicyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x0eprimary_source\x18\x02 \x01(\tR\rprimarySource\x12'\n" +
	"\x0ffallback_source\x18\x03 \x01(\tR\x0efallbackSource\x12)\n" +
	"\x10fallback_enabled\x18\x04 \x01(\bR\x0ffallbackEnabled\x12,\n" +
	"\x12dynamic_timeout_ms\x18\x05 \x01(\x05R\x10dynamicTimeoutMs\x12.\n" +
	"\x13dynamic_retry_count\x18\x06 \x01(\x05R\x11dynamicRetryCount\x12=\n" +
	"\x1bdynamic_circuit_breaker_sec\x18\a \x01(\x05R\x18dynamicCircuitBreakerSec\x12)\n" +
	"\x11min_lease_ttl_sec\x18\b \x01(\x05R\x0eminLeaseTtlSec\x12:\n" +
	"\x19manual_selection_strategy\x18\t \x01(\tR\x17manualSelectionStrategy\"\xad\x03\n" +
	"\x0eAdminProxyInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12#\n" +
	"\rplatform_tags\x18\b \x01(\tR\fplatformTags\x12\x16\n" +
	"\x06remark\x18\t \x01(\tR\x06remark\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12 \n" +
	"\flast_used_at\x18\v \x01(\tR\n" +
	"lastUsedAt\x12#\n" +
	"\rsuccess_count\x18\f \x01(\x05R\fsuccessCount\x12\x1d\n" +
	"\n" +
	"fail_count\x18\r \x01(\x05R\tfailCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAt\"\x9c\x01\n" +
	"\x17AdminListProxiesRequest\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"has_status\x18\x05 \x01(\bR\thasStatus\"G\n" +
	"\x18AdminListProxiesResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.admin.AdminProxyInfoR\x05items\"\x9e\x02\n" +
	"\x17AdminCreateProxyRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12#\n" +
	"\rplatform_tags\x18\b \x01(\tR\fplatformTags\x12\x16\n" +
	"\x06remark\x18\t \x01(\tR\x06remark\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\"\x96\x02\n" +
	"\x17AdminUpdateProxyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12\x16\n" +
	"\x06region\x18\a \x01(\tR\x06region\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriority\x12#\n" +
	"\rplatform_tags\x18\t \x01(\tR\fplatformTags\x12\x16\n" +
	"\x06remark\x18\n" +
	" \x01(\tR\x06remark\"G\n" +
	"\x1dAdminUpdateProxyStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"$\n" +
	"\x12AdminDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xab\x03\n" +
	"\x0fAdminCookieInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1b\n" +
	"\texpire_at\x18\x06 \x01(\tR\bexpireAt\x12!\n" +
	"\ffrozen_until\x18\a \x01(\tR\vfrozenUntil\x12%\n" +
	"\x0efreeze_seconds\x18\b \x01(\x05R\rfreezeSeconds\x12 \n" +
	"\flast_used_at\x18\t \x01(\tR\n" +
	"lastUsedAt\x12\x1b\n" +
	"\tuse_count\x18\n" +
	" \x01(\x03R\buseCount\x12#\n" +
	"\rsuccess_count\x18\v \x01(\x03R\fsuccessCount\x12\x1d\n" +
	"\n" +
	"fail_count\x18\f \x01(\x03R\tfailCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\"~\n" +
	"\x17AdminListCookiesRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x8f\x01\n" +
	"\x18AdminListCookiesResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12,\n" +
	"\x05items\x18\x04 \x03(\v2\x16.admin.AdminCookieInfoR\x05items\"'\n" +
	"\x15AdminGetCookieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"H\n" +
	"\x16AdminGetCookieResponse\x12.\n" +
	"\x06cookie\x18\x01 \x01(\v2\x16.admin.AdminCookieInfoR\x06cookie\"\xa8\x01\n" +
	"\x18AdminCreateCookieRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\texpire_at\x18\x04 \x01(\tR\bexpireAt\x12%\n" +
	"\x0efreeze_seconds\x18\x05 \x01(\x05R\rfreezeSeconds\"\x9c\x01\n" +
	"\x18AdminUpdateCookieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\texpire_at\x18\x04 \x01(\tR\bexpireAt\x12%\n" +
	"\x0efreeze_seconds\x18\x05 \x01(\x05R\rfreezeSeconds\"Q\n" +
	"\x18AdminFreezeCookieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x0efreeze_seconds\x18\x02 \x01(\x05R\rfreezeSeconds\"X\n" +
	"\x19AdminFreezeCookieResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\ffrozen_until\x18\x02 \x01(\tR\vfrozenUntil\"-\n" +
	"\x1bAdminCreateResourceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"2\n" +
	"\x16AdminOperationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xb1\f\n" +
	"\fAdminService\x12<\n" +
	"\x05Login\x12\x18.admin.AdminLoginRequest\x1a\x19.admin.AdminLoginResponse\x12B\n" +
	"\x06Logout\x12\x19.admin.AdminLogoutRequest\x1a\x1d.admin.AdminOperationResponse\x12M\n" +
	"\x0eGetCurrentUser\x12\x1a.admin.AdminSessionRequest\x1a\x1f.admin.AdminCurrentUserResponse\x12>\n" +
	"\vGetOverview\x12\x11.admin.AdminEmpty\x1a\x1c.admin.AdminOverviewResponse\x12T\n" +
	"\x0fGetRequestTrend\x12\x1f.admin.AdminRequestTrendRequest\x1a .admin.AdminRequestTrendResponse\x12@\n" +
	"\fGetUserStats\x12\x11.admin.AdminEmpty\x1a\x1d.admin.AdminUserStatsResponse\x12P\n" +
	"\x14GetProxySourceStatus\x12\x11.admin.AdminEmpty\x1a%.admin.AdminProxySourceStatusResponse\x12P\n" +
	"\x14GetProxySourcePolicy\x12\x11.admin.AdminEmpty\x1a%.admin.AdminProxySourcePolicyResponse\x12d\n" +
	"\x17UpdateProxySourcePolicy\x12*.admin.AdminUpdateProxySourcePolicyRequest\x1a\x1d.admin.AdminOperationResponse\x12N\n" +
	"\vListProxies\x12\x1e.admin.AdminListProxiesRequest\x1a\x1f.admin.AdminListProxiesResponse\x12Q\n" +
	"\vCreateProxy\x12\x1e.admin.AdminCreateProxyRequest\x1a\".admin.AdminCreateResourceResponse\x12L\n" +
	"\vUpdateProxy\x12\x1e.admin.AdminUpdateProxyRequest\x1a\x1d.admin.AdminOperationResponse\x12X\n" +
	"\x11UpdateProxyStatus\x12$.admin.AdminUpdateProxyStatusRequest\x1a\x1d.admin.AdminOperationResponse\x12G\n" +
	"\vDeleteProxy\x12\x19.admin.AdminDeleteRequest\x1a\x1d.admin.AdminOperationResponse\x12N\n" +
	"\vListCookies\x12\x1e.admin.AdminListCookiesRequest\x1a\x1f.admin.AdminListCookiesResponse\x12H\n" +
	"\tGetCookie\x12\x1c.admin.AdminGetCookieRequest\x1a\x1d.admin.AdminGetCookieResponse\x12S\n" +
	"\fCreateCookie\x12\x1f.admin.AdminCreateCookieRequest\x1a\".admin.AdminCreateResourceResponse\x12N\n" +
	"\fUpdateCookie\x12\x1f.admin.AdminUpdateCookieRequest\x1a\x1d.admin.AdminOperationResponse\x12H\n" +
	"\fDeleteCookie\x12\x19.admin.AdminDeleteRequest\x1a\x1d.admin.AdminOperationResponse\x12Q\n" +
	"\fFreezeCookie\x12\x1f.admin.AdminFreezeCookieRequest\x1a .admin.AdminFreezeCookieResponseB\x1fZ\x1dvasset/admin-service/proto;pbb\x06proto3"

var (
	file_proto_admin_proto_rawDescOnce sync.Once
	file_proto_admin_proto_rawDescData []byte
)

func file_proto_admin_proto_rawDescGZIP() []byte {
	file_proto_admin_proto_rawDescOnce.Do(func() {
		file_proto_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_proto_rawDesc), len(file_proto_admin_proto_rawDesc)))
	})
	return file_proto_admin_proto_rawDescData
}

var file_proto_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_proto_admin_proto_goTypes = []any{
	(*AdminEmpty)(nil),                          // 0: admin.AdminEmpty
	(*AdminUser)(nil),                           // 1: admin.AdminUser
	(*AdminLoginRequest)(nil),                   // 2: admin.AdminLoginRequest
	(*AdminLoginResponse)(nil),                  // 3: admin.AdminLoginResponse
	(*AdminLogoutRequest)(nil),                  // 4: admin.AdminLogoutRequest
	(*AdminSessionRequest)(nil),                 // 5: admin.AdminSessionRequest
	(*AdminCurrentUserResponse)(nil),            // 6: admin.AdminCurrentUserResponse
	(*AdminOverviewResponse)(nil),               // 7: admin.AdminOverviewResponse
	(*AdminTrendPoint)(nil),                     // 8: admin.AdminTrendPoint
	(*AdminRequestTrendRequest)(nil),            // 9: admin.AdminRequestTrendRequest
	(*AdminRequestTrendResponse)(nil),           // 10: admin.AdminRequestTrendResponse
	(*AdminUserStatsResponse)(nil),              // 11: admin.AdminUserStatsResponse
	(*AdminProxySourceStatusResponse)(nil),      // 12: admin.AdminProxySourceStatusResponse
	(*AdminProxySourcePolicyResponse)(nil),      // 13: admin.AdminProxySourcePolicyResponse
	(*AdminUpdateProxySourcePolicyRequest)(nil), // 14: admin.AdminUpdateProxySourcePolicyRequest
	(*AdminProxyInfo)(nil),                      // 15: admin.AdminProxyInfo
	(*AdminListProxiesRequest)(nil),             // 16: admin.AdminListProxiesRequest
	(*AdminListProxiesResponse)(nil),            // 17: admin.AdminListProxiesResponse
	(*AdminCreateProxyRequest)(nil),             // 18: admin.AdminCreateProxyRequest
	(*AdminUpdateProxyRequest)(nil),             // 19: admin.AdminUpdateProxyRequest
	(*AdminUpdateProxyStatusRequest)(nil),       // 20: admin.AdminUpdateProxyStatusRequest
	(*AdminDeleteRequest)(nil),                  // 21: admin.AdminDeleteRequest
	(*AdminCookieInfo)(nil),                     // 22: admin.AdminCookieInfo
	(*AdminListCookiesRequest)(nil),             // 23: admin.AdminListCookiesRequest
	(*AdminListCookiesResponse)(nil),            // 24: admin.AdminListCookiesResponse
	(*AdminGetCookieRequest)(nil),               // 25: admin.AdminGetCookieRequest
	(*AdminGetCookieResponse)(nil),              // 26: admin.AdminGetCookieResponse
	(*AdminCreateCookieRequest)(nil),            // 27: admin.AdminCreateCookieRequest
	(*AdminUpdateCookieRequest)(nil),            // 28: admin.AdminUpdateCookieRequest
	(*AdminFreezeCookieRequest)(nil),            // 29: admin.AdminFreezeCookieRequest
	(*AdminFreezeCookieResponse)(nil),           // 30: admin.AdminFreezeCookieResponse
	(*AdminCreateResourceResponse)(nil),         // 31: admin.AdminCreateResourceResponse
	(*AdminOperationResponse)(nil),              // 32: admin.AdminOperationResponse
}
var file_proto_admin_proto_depIdxs = []int32{
	1,  // 0: admin.AdminLoginResponse.user:type_name -> admin.AdminUser
	1,  // 1: admin.AdminCurrentUserResponse.user:type_name -> admin.AdminUser
	8,  // 2: admin.AdminRequestTrendResponse.points:type_name -> admin.AdminTrendPoint
	15, // 3: admin.AdminListProxiesResponse.items:type_name -> admin.AdminProxyInfo
	22, // 4: admin.AdminListCookiesResponse.items:type_name -> admin.AdminCookieInfo
	22, // 5: admin.AdminGetCookieResponse.cookie:type_name -> admin.AdminCookieInfo
	2,  // 6: admin.AdminService.Login:input_type -> admin.AdminLoginRequest
	4,  // 7: admin.AdminService.Logout:input_type -> admin.AdminLogoutRequest
	5,  // 8: admin.AdminService.GetCurrentUser:input_type -> admin.AdminSessionRequest
	0,  // 9: admin.AdminService.GetOverview:input_type -> admin.AdminEmpty
	9,  // 10: admin.AdminService.GetRequestTrend:input_type -> admin.AdminRequestTrendRequest
	0,  // 11: admin.AdminService.GetUserStats:input_type -> admin.AdminEmpty
	0,  // 12: admin.AdminService.GetProxySourceStatus:input_type -> admin.AdminEmpty
	0,  // 13: admin.AdminService.GetProxySourcePolicy:input_type -> admin.AdminEmpty
	14, // 14: admin.AdminService.UpdateProxySourcePolicy:input_type -> admin.AdminUpdateProxySourcePolicyRequest
	16, // 15: admin.AdminService.ListProxies:input_type -> admin.AdminListProxiesRequest
	18, // 16: admin.AdminService.CreateProxy:input_type -> admin.AdminCreateProxyRequest
	19, // 17: admin.AdminService.UpdateProxy:input_type -> admin.AdminUpdateProxyRequest
	20, // 18: admin.AdminService.UpdateProxyStatus:input_type -> admin.AdminUpdateProxyStatusRequest
	21, // 19: admin.AdminService.DeleteProxy:input_type -> admin.AdminDeleteRequest
	23, // 20: admin.AdminService.ListCookies:input_type -> admin.AdminListCookiesRequest
	25, // 21: admin.AdminService.GetCookie:input_type -> admin.AdminGetCookieRequest
	27, // 22: admin.AdminService.CreateCookie:input_type -> admin.AdminCreateCookieRequest
	28, // 23: admin.AdminService.UpdateCookie:input_type -> admin.AdminUpdateCookieRequest
	21, // 24: admin.AdminService.DeleteCookie:input_type -> admin.AdminDeleteRequest
	29, // 25: admin.AdminService.FreezeCookie:input_type -> admin.AdminFreezeCookieRequest
	3,  // 26: admin.AdminService.Login:output_type -> admin.AdminLoginResponse
	32, // 27: admin.AdminService.Logout:output_type -> admin.AdminOperationResponse
	6,  // 28: admin.AdminService.GetCurrentUser:output_type -> admin.AdminCurrentUserResponse
	7,  // 29: admin.AdminService.GetOverview:output_type -> admin.AdminOverviewResponse
	10, // 30: admin.AdminService.GetRequestTrend:output_type -> admin.AdminRequestTrendResponse
	11, // 31: admin.AdminService.GetUserStats:output_type -> admin.AdminUserStatsResponse
	12, // 32: admin.AdminService.GetProxySourceStatus:output_type -> admin.AdminProxySourceStatusResponse
	13, // 33: admin.AdminService.GetProxySourcePolicy:output_type -> admin.AdminProxySourcePolicyResponse
	32, // 34: admin.AdminService.UpdateProxySourcePolicy:output_type -> admin.AdminOperationResponse
	17, // 35: admin.AdminService.ListProxies:output_type -> admin.AdminListProxiesResponse
	31, // 36: admin.AdminService.CreateProxy:output_type -> admin.AdminCreateResourceResponse
	32, // 37: admin.AdminService.UpdateProxy:output_type -> admin.AdminOperationResponse
	32, // 38: admin.AdminService.UpdateProxyStatus:output_type -> admin.AdminOperationResponse
	32, // 39: admin.AdminService.DeleteProxy:output_type -> admin.AdminOperationResponse
	24, // 40: admin.AdminService.ListCookies:output_type -> admin.AdminListCookiesResponse
	26, // 41: admin.AdminService.GetCookie:output_type -> admin.AdminGetCookieResponse
	31, // 42: admin.AdminService.CreateCookie:output_type -> admin.AdminCreateResourceResponse
	32, // 43: admin.AdminService.UpdateCookie:output_type -> admin.AdminOperationResponse
	32, // 44: admin.AdminService.DeleteCookie:output_type -> admin.AdminOperationResponse
	30, // 45: admin.AdminService.FreezeCookie:output_type -> admin.AdminFreezeCookieResponse
	26, // [26:46] is the sub-list for method output_type
	6,  // [6:26] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_admin_proto_init() }
func file_proto_admin_proto_init() {
	if File_proto_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_proto_rawDesc), len(file_proto_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_proto_goTypes,
		DependencyIndexes: file_proto_admin_proto_depIdxs,
		MessageInfos:      file_proto_admin_proto_msgTypes,
	}.Build()
	File_proto_admin_proto = out.File
	file_proto_admin_proto_goTypes = nil
	file_proto_admin_proto_depIdxs = nil
}
