// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/asset.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPlatformStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlatformStatsRequest) Reset() {
	*x = GetPlatformStatsRequest{}
	mi := &file_proto_asset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformStatsRequest) ProtoMessage() {}

func (x *GetPlatformStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformStatsRequest.ProtoReflect.Descriptor instead.
func (*GetPlatformStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{0}
}

type GetPlatformStatsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalDownloads    int64                  `protobuf:"varint,1,opt,name=total_downloads,json=totalDownloads,proto3" json:"total_downloads,omitempty"`
	SuccessDownloads  int64                  `protobuf:"varint,2,opt,name=success_downloads,json=successDownloads,proto3" json:"success_downloads,omitempty"`
	FailedDownloads   int64                  `protobuf:"varint,3,opt,name=failed_downloads,json=failedDownloads,proto3" json:"failed_downloads,omitempty"`
	DownloadsToday    int64                  `protobuf:"varint,4,opt,name=downloads_today,json=downloadsToday,proto3" json:"downloads_today,omitempty"`
	DailyActiveUsers  int64                  `protobuf:"varint,5,opt,name=daily_active_users,json=dailyActiveUsers,proto3" json:"daily_active_users,omitempty"`
	WeeklyActiveUsers int64                  `protobuf:"varint,6,opt,name=weekly_active_users,json=weeklyActiveUsers,proto3" json:"weekly_active_users,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetPlatformStatsResponse) Reset() {
	*x = GetPlatformStatsResponse{}
	mi := &file_proto_asset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformStatsResponse) ProtoMessage() {}

func (x *GetPlatformStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformStatsResponse.ProtoReflect.Descriptor instead.
func (*GetPlatformStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlatformStatsResponse) GetTotalDownloads() int64 {
	if x != nil {
		return x.TotalDownloads
	}
	return 0
}

func (x *GetPlatformStatsResponse) GetSuccessDownloads() int64 {
	if x != nil {
		return x.SuccessDownloads
	}
	return 0
}

func (x *GetPlatformStatsResponse) GetFailedDownloads() int64 {
	if x != nil {
		return x.FailedDownloads
	}
	return 0
}

func (x *GetPlatformStatsResponse) GetDownloadsToday() int64 {
	if x != nil {
		return x.DownloadsToday
	}
	return 0
}

func (x *GetPlatformStatsResponse) GetDailyActiveUsers() int64 {
	if x != nil {
		return x.DailyActiveUsers
	}
	return 0
}

func (x *GetPlatformStatsResponse) GetWeeklyActiveUsers() int64 {
	if x != nil {
		return x.WeeklyActiveUsers
	}
	return 0
}

type GetRequestTrendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Granularity   string                 `protobuf:"bytes,1,opt,name=granularity,proto3" json:"granularity,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequestTrendRequest) Reset() {
	*x = GetRequestTrendRequest{}
	mi := &file_proto_asset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequestTrendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestTrendRequest) ProtoMessage() {}

func (x *GetRequestTrendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestTrendRequest.ProtoReflect.Descriptor instead.
func (*GetRequestTrendRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequestTrendRequest) GetGranularity() string {
	if x != nil {
		return x.Granularity
	}
	return ""
}

func (x *GetRequestTrendRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TrendPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendPoint) Reset() {
	*x = TrendPoint{}
	mi := &file_proto_asset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendPoint) ProtoMessage() {}

func (x *TrendPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendPoint.ProtoReflect.Descriptor instead.
func (*TrendPoint) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{3}
}

func (x *TrendPoint) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TrendPoint) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetRequestTrendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Granularity   string                 `protobuf:"bytes,1,opt,name=granularity,proto3" json:"granularity,omitempty"`
	Points        []*TrendPoint          `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequestTrendResponse) Reset() {
	*x = GetRequestTrendResponse{}
	mi := &file_proto_asset_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequestTrendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestTrendResponse) ProtoMessage() {}

func (x *GetRequestTrendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestTrendResponse.ProtoReflect.Descriptor instead.
func (*GetRequestTrendResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequestTrendResponse) GetGranularity() string {
	if x != nil {
		return x.Granularity
	}
	return ""
}

func (x *GetRequestTrendResponse) GetPoints() []*TrendPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type GetAvailableProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableProxyRequest) Reset() {
	*x = GetAvailableProxyRequest{}
	mi := &file_proto_asset_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableProxyRequest) ProtoMessage() {}

func (x *GetAvailableProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableProxyRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableProxyRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{5}
}

func (x *GetAvailableProxyRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *GetAvailableProxyRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type GetAvailableProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProxyUrl      string                 `protobuf:"bytes,1,opt,name=proxy_url,json=proxyUrl,proto3" json:"proxy_url,omitempty"`
	ProxyLeaseId  string                 `protobuf:"bytes,2,opt,name=proxy_lease_id,json=proxyLeaseId,proto3" json:"proxy_lease_id,omitempty"`
	ExpireAt      string                 `protobuf:"bytes,3,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableProxyResponse) Reset() {
	*x = GetAvailableProxyResponse{}
	mi := &file_proto_asset_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableProxyResponse) ProtoMessage() {}

func (x *GetAvailableProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableProxyResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableProxyResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{6}
}

func (x *GetAvailableProxyResponse) GetProxyUrl() string {
	if x != nil {
		return x.ProxyUrl
	}
	return ""
}

func (x *GetAvailableProxyResponse) GetProxyLeaseId() string {
	if x != nil {
		return x.ProxyLeaseId
	}
	return ""
}

func (x *GetAvailableProxyResponse) GetExpireAt() string {
	if x != nil {
		return x.ExpireAt
	}
	return ""
}

type GetProxySourcePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProxySourcePolicyRequest) Reset() {
	*x = GetProxySourcePolicyRequest{}
	mi := &file_proto_asset_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProxySourcePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProxySourcePolicyRequest) ProtoMessage() {}

func (x *GetProxySourcePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProxySourcePolicyRequest.ProtoReflect.Descriptor instead.
func (*GetProxySourcePolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{7}
}

type GetProxySourcePolicyResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Id                       int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ScopeType                string                 `protobuf:"bytes,2,opt,name=scope_type,json=scopeType,proto3" json:"scope_type,omitempty"`
	ScopeValue               string                 `protobuf:"bytes,3,opt,name=scope_value,json=scopeValue,proto3" json:"scope_value,omitempty"`
	PrimarySource            string                 `protobuf:"bytes,4,opt,name=primary_source,json=primarySource,proto3" json:"primary_source,omitempty"`
	FallbackSource           string                 `protobuf:"bytes,5,opt,name=fallback_source,json=fallbackSource,proto3" json:"fallback_source,omitempty"`
	FallbackEnabled          bool                   `protobuf:"varint,6,opt,name=fallback_enabled,json=fallbackEnabled,proto3" json:"fallback_enabled,omitempty"`
	DynamicTimeoutMs         int32                  `protobuf:"varint,7,opt,name=dynamic_timeout_ms,json=dynamicTimeoutMs,proto3" json:"dynamic_timeout_ms,omitempty"`
	DynamicRetryCount        int32                  `protobuf:"varint,8,opt,name=dynamic_retry_count,json=dynamicRetryCount,proto3" json:"dynamic_retry_count,omitempty"`
	DynamicCircuitBreakerSec int32                  `protobuf:"varint,9,opt,name=dynamic_circuit_breaker_sec,json=dynamicCircuitBreakerSec,proto3" json:"dynamic_circuit_breaker_sec,omitempty"`
	MinLeaseTtlSec           int32                  `protobuf:"varint,10,opt,name=min_lease_ttl_sec,json=minLeaseTtlSec,proto3" json:"min_lease_ttl_sec,omitempty"`
	ManualSelectionStrategy  string                 `protobuf:"bytes,11,opt,name=manual_selection_strategy,json=manualSelectionStrategy,proto3" json:"manual_selection_strategy,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GetProxySourcePolicyResponse) Reset() {
	*x = GetProxySourcePolicyResponse{}
	mi := &file_proto_asset_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProxySourcePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProxySourcePolicyResponse) ProtoMessage() {}

func (x *GetProxySourcePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProxySourcePolicyResponse.ProtoReflect.Descriptor instead.
func (*GetProxySourcePolicyResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{8}
}

func (x *GetProxySourcePolicyResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetProxySourcePolicyResponse) GetScopeType() string {
	if x != nil {
		return x.ScopeType
	}
	return ""
}

func (x *GetProxySourcePolicyResponse) GetScopeValue() string {
	if x != nil {
		return x.ScopeValue
	}
	return ""
}

func (x *GetProxySourcePolicyResponse) GetPrimarySource() string {
	if x != nil {
		return x.PrimarySource
	}
	return ""
}

func (x *GetProxySourcePolicyResponse) GetFallbackSource() string {
	if x != nil {
		return x.FallbackSource
	}
	return ""
}

func (x *GetProxySourcePolicyResponse) GetFallbackEnabled() bool {
	if x != nil {
		return x.FallbackEnabled
	}
	return false
}

func (x *GetProxySourcePolicyResponse) GetDynamicTimeoutMs() int32 {
	if x != nil {
		return x.DynamicTimeoutMs
	}
	return 0
}

func (x *GetProxySourcePolicyResponse) GetDynamicRetryCount() int32 {
	if x != nil {
		return x.DynamicRetryCount
	}
	return 0
}

func (x *GetProxySourcePolicyResponse) GetDynamicCircuitBreakerSec() int32 {
	if x != nil {
		return x.DynamicCircuitBreakerSec
	}
	return 0
}

func (x *GetProxySourcePolicyResponse) GetMinLeaseTtlSec() int32 {
	if x != nil {
		return x.MinLeaseTtlSec
	}
	return 0
}

func (x *GetProxySourcePolicyResponse) GetManualSelectionStrategy() string {
	if x != nil {
		return x.ManualSelectionStrategy
	}
	return ""
}

type UpdateProxySourcePolicyRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Id                       int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PrimarySource            string                 `protobuf:"bytes,2,opt,name=primary_source,json=primarySource,proto3" json:"primary_source,omitempty"`
	FallbackSource           string                 `protobuf:"bytes,3,opt,name=fallback_source,json=fallbackSource,proto3" json:"fallback_source,omitempty"`
	FallbackEnabled          bool                   `protobuf:"varint,4,opt,name=fallback_enabled,json=fallbackEnabled,proto3" json:"fallback_enabled,omitempty"`
	DynamicTimeoutMs         int32                  `protobuf:"varint,5,opt,name=dynamic_timeout_ms,json=dynamicTimeoutMs,proto3" json:"dynamic_timeout_ms,omitempty"`
	DynamicRetryCount        int32                  `protobuf:"varint,6,opt,name=dynamic_retry_count,json=dynamicRetryCount,proto3" json:"dynamic_retry_count,omitempty"`
	DynamicCircuitBreakerSec int32                  `protobuf:"varint,7,opt,name=dynamic_circuit_breaker_sec,json=dynamicCircuitBreakerSec,proto3" json:"dynamic_circuit_breaker_sec,omitempty"`
	MinLeaseTtlSec           int32                  `protobuf:"varint,8,opt,name=min_lease_ttl_sec,json=minLeaseTtlSec,proto3" json:"min_lease_ttl_sec,omitempty"`
	ManualSelectionStrategy  string                 `protobuf:"bytes,9,opt,name=manual_selection_strategy,json=manualSelectionStrategy,proto3" json:"manual_selection_strategy,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *UpdateProxySourcePolicyRequest) Reset() {
	*x = UpdateProxySourcePolicyRequest{}
	mi := &file_proto_asset_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProxySourcePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProxySourcePolicyRequest) ProtoMessage() {}

func (x *UpdateProxySourcePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProxySourcePolicyRequest.ProtoReflect.Descriptor instead.
func (*UpdateProxySourcePolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProxySourcePolicyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProxySourcePolicyRequest) GetPrimarySource() string {
	if x != nil {
		return x.PrimarySource
	}
	return ""
}

func (x *UpdateProxySourcePolicyRequest) GetFallbackSource() string {
	if x != nil {
		return x.FallbackSource
	}
	return ""
}

func (x *UpdateProxySourcePolicyRequest) GetFallbackEnabled() bool {
	if x != nil {
		return x.FallbackEnabled
	}
	return false
}

func (x *UpdateProxySourcePolicyRequest) GetDynamicTimeoutMs() int32 {
	if x != nil {
		return x.DynamicTimeoutMs
	}
	return 0
}

func (x *UpdateProxySourcePolicyRequest) GetDynamicRetryCount() int32 {
	if x != nil {
		return x.DynamicRetryCount
	}
	return 0
}

func (x *UpdateProxySourcePolicyRequest) GetDynamicCircuitBreakerSec() int32 {
	if x != nil {
		return x.DynamicCircuitBreakerSec
	}
	return 0
}

func (x *UpdateProxySourcePolicyRequest) GetMinLeaseTtlSec() int32 {
	if x != nil {
		return x.MinLeaseTtlSec
	}
	return 0
}

func (x *UpdateProxySourcePolicyRequest) GetManualSelectionStrategy() string {
	if x != nil {
		return x.ManualSelectionStrategy
	}
	return ""
}

type UpdateProxySourcePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProxySourcePolicyResponse) Reset() {
	*x = UpdateProxySourcePolicyResponse{}
	mi := &file_proto_asset_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProxySourcePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProxySourcePolicyResponse) ProtoMessage() {}

func (x *UpdateProxySourcePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProxySourcePolicyResponse.ProtoReflect.Descriptor instead.
func (*UpdateProxySourcePolicyResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateProxySourcePolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ProxyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Region        string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	PlatformTags  string                 `protobuf:"bytes,8,opt,name=platform_tags,json=platformTags,proto3" json:"platform_tags,omitempty"`
	Remark        string                 `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	LastUsedAt    string                 `protobuf:"bytes,11,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	SuccessCount  int32                  `protobuf:"varint,12,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailCount     int32                  `protobuf:"varint,13,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyInfo) Reset() {
	*x = ProxyInfo{}
	mi := &file_proto_asset_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyInfo) ProtoMessage() {}

func (x *ProxyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyInfo.ProtoReflect.Descriptor instead.
func (*ProxyInfo) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{11}
}

func (x *ProxyInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProxyInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ProxyInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ProxyInfo) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ProxyInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProxyInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ProxyInfo) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ProxyInfo) GetPlatformTags() string {
	if x != nil {
		return x.PlatformTags
	}
	return ""
}

func (x *ProxyInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *ProxyInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProxyInfo) GetLastUsedAt() string {
	if x != nil {
		return x.LastUsedAt
	}
	return ""
}

func (x *ProxyInfo) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *ProxyInfo) GetFailCount() int32 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

func (x *ProxyInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ProxyInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListProxiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProxiesRequest) Reset() {
	*x = ListProxiesRequest{}
	mi := &file_proto_asset_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProxiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProxiesRequest) ProtoMessage() {}

func (x *ListProxiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProxiesRequest.ProtoReflect.Descriptor instead.
func (*ListProxiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{12}
}

func (x *ListProxiesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListProxiesRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ListProxiesRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ListProxiesRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListProxiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ProxyInfo           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProxiesResponse) Reset() {
	*x = ListProxiesResponse{}
	mi := &file_proto_asset_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProxiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProxiesResponse) ProtoMessage() {}

func (x *ListProxiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProxiesResponse.ProtoReflect.Descriptor instead.
func (*ListProxiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{13}
}

func (x *ListProxiesResponse) GetItems() []*ProxyInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Region        string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	PlatformTags  string                 `protobuf:"bytes,8,opt,name=platform_tags,json=platformTags,proto3" json:"platform_tags,omitempty"`
	Remark        string                 `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProxyRequest) Reset() {
	*x = CreateProxyRequest{}
	mi := &file_proto_asset_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProxyRequest) ProtoMessage() {}

func (x *CreateProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProxyRequest.ProtoReflect.Descriptor instead.
func (*CreateProxyRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{14}
}

func (x *CreateProxyRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *CreateProxyRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CreateProxyRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *CreateProxyRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateProxyRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateProxyRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CreateProxyRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateProxyRequest) GetPlatformTags() string {
	if x != nil {
		return x.PlatformTags
	}
	return ""
}

func (x *CreateProxyRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *CreateProxyRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProxyResponse) Reset() {
	*x = CreateProxyResponse{}
	mi := &file_proto_asset_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProxyResponse) ProtoMessage() {}

func (x *CreateProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProxyResponse.ProtoReflect.Descriptor instead.
func (*CreateProxyResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{15}
}

func (x *CreateProxyResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Region        string                 `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`
	Priority      int32                  `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	PlatformTags  string                 `protobuf:"bytes,9,opt,name=platform_tags,json=platformTags,proto3" json:"platform_tags,omitempty"`
	Remark        string                 `protobuf:"bytes,10,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProxyRequest) Reset() {
	*x = UpdateProxyRequest{}
	mi := &file_proto_asset_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProxyRequest) ProtoMessage() {}

func (x *UpdateProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProxyRequest.ProtoReflect.Descriptor instead.
func (*UpdateProxyRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateProxyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProxyRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *UpdateProxyRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *UpdateProxyRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *UpdateProxyRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateProxyRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateProxyRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *UpdateProxyRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *UpdateProxyRequest) GetPlatformTags() string {
	if x != nil {
		return x.PlatformTags
	}
	return ""
}

func (x *UpdateProxyRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type UpdateProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProxyResponse) Reset() {
	*x = UpdateProxyResponse{}
	mi := &file_proto_asset_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProxyResponse) ProtoMessage() {}

func (x *UpdateProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProxyResponse.ProtoReflect.Descriptor instead.
func (*UpdateProxyResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateProxyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateProxyStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProxyStatusRequest) Reset() {
	*x = UpdateProxyStatusRequest{}
	mi := &file_proto_asset_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProxyStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProxyStatusRequest) ProtoMessage() {}

func (x *UpdateProxyStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProxyStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateProxyStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateProxyStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProxyStatusRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateProxyStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProxyStatusResponse) Reset() {
	*x = UpdateProxyStatusResponse{}
	mi := &file_proto_asset_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProxyStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProxyStatusResponse) ProtoMessage() {}

func (x *UpdateProxyStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProxyStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateProxyStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateProxyStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProxyRequest) Reset() {
	*x = DeleteProxyRequest{}
	mi := &file_proto_asset_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProxyRequest) ProtoMessage() {}

func (x *DeleteProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProxyRequest.ProtoReflect.Descriptor instead.
func (*DeleteProxyRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteProxyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProxyResponse) Reset() {
	*x = DeleteProxyResponse{}
	mi := &file_proto_asset_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProxyResponse) ProtoMessage() {}

func (x *DeleteProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProxyResponse.ProtoReflect.Descriptor instead.
func (*DeleteProxyResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteProxyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CookieInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	ExpireAt      string                 `protobuf:"bytes,6,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	FrozenUntil   string                 `protobuf:"bytes,7,opt,name=frozen_until,json=frozenUntil,proto3" json:"frozen_until,omitempty"`
	FreezeSeconds int32                  `protobuf:"varint,8,opt,name=freeze_seconds,json=freezeSeconds,proto3" json:"freeze_seconds,omitempty"`
	LastUsedAt    string                 `protobuf:"bytes,9,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	UseCount      int32                  `protobuf:"varint,10,opt,name=use_count,json=useCount,proto3" json:"use_count,omitempty"`
	SuccessCount  int32                  `protobuf:"varint,11,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailCount     int32                  `protobuf:"varint,12,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CookieInfo) Reset() {
	*x = CookieInfo{}
	mi := &file_proto_asset_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CookieInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CookieInfo) ProtoMessage() {}

func (x *CookieInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CookieInfo.ProtoReflect.Descriptor instead.
func (*CookieInfo) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{22}
}

func (x *CookieInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CookieInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CookieInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CookieInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CookieInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CookieInfo) GetExpireAt() string {
	if x != nil {
		return x.ExpireAt
	}
	return ""
}

func (x *CookieInfo) GetFrozenUntil() string {
	if x != nil {
		return x.FrozenUntil
	}
	return ""
}

func (x *CookieInfo) GetFreezeSeconds() int32 {
	if x != nil {
		return x.FreezeSeconds
	}
	return 0
}

func (x *CookieInfo) GetLastUsedAt() string {
	if x != nil {
		return x.LastUsedAt
	}
	return ""
}

func (x *CookieInfo) GetUseCount() int32 {
	if x != nil {
		return x.UseCount
	}
	return 0
}

func (x *CookieInfo) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *CookieInfo) GetFailCount() int32 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

func (x *CookieInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CookieInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateCookieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ExpireAt      string                 `protobuf:"bytes,4,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	FreezeSeconds int32                  `protobuf:"varint,5,opt,name=freeze_seconds,json=freezeSeconds,proto3" json:"freeze_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCookieRequest) Reset() {
	*x = CreateCookieRequest{}
	mi := &file_proto_asset_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCookieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCookieRequest) ProtoMessage() {}

func (x *CreateCookieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCookieRequest.ProtoReflect.Descriptor instead.
func (*CreateCookieRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{23}
}

func (x *CreateCookieRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CreateCookieRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCookieRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateCookieRequest) GetExpireAt() string {
	if x != nil {
		return x.ExpireAt
	}
	return ""
}

func (x *CreateCookieRequest) GetFreezeSeconds() int32 {
	if x != nil {
		return x.FreezeSeconds
	}
	return 0
}

type CreateCookieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCookieResponse) Reset() {
	*x = CreateCookieResponse{}
	mi := &file_proto_asset_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCookieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCookieResponse) ProtoMessage() {}

func (x *CreateCookieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCookieResponse.ProtoReflect.Descriptor instead.
func (*CreateCookieResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{24}
}

func (x *CreateCookieResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateCookieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ExpireAt      string                 `protobuf:"bytes,4,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	FreezeSeconds int32                  `protobuf:"varint,5,opt,name=freeze_seconds,json=freezeSeconds,proto3" json:"freeze_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCookieRequest) Reset() {
	*x = UpdateCookieRequest{}
	mi := &file_proto_asset_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCookieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCookieRequest) ProtoMessage() {}

func (x *UpdateCookieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCookieRequest.ProtoReflect.Descriptor instead.
func (*UpdateCookieRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateCookieRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCookieRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCookieRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateCookieRequest) GetExpireAt() string {
	if x != nil {
		return x.ExpireAt
	}
	return ""
}

func (x *UpdateCookieRequest) GetFreezeSeconds() int32 {
	if x != nil {
		return x.FreezeSeconds
	}
	return 0
}

type UpdateCookieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCookieResponse) Reset() {
	*x = UpdateCookieResponse{}
	mi := &file_proto_asset_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCookieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCookieResponse) ProtoMessage() {}

func (x *UpdateCookieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCookieResponse.ProtoReflect.Descriptor instead.
func (*UpdateCookieResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateCookieResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteCookieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCookieRequest) Reset() {
	*x = DeleteCookieRequest{}
	mi := &file_proto_asset_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCookieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCookieRequest) ProtoMessage() {}

func (x *DeleteCookieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCookieRequest.ProtoReflect.Descriptor instead.
func (*DeleteCookieRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteCookieRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCookieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCookieResponse) Reset() {
	*x = DeleteCookieResponse{}
	mi := &file_proto_asset_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCookieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCookieResponse) ProtoMessage() {}

func (x *DeleteCookieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCookieResponse.ProtoReflect.Descriptor instead.
func (*DeleteCookieResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteCookieResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetCookieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCookieRequest) Reset() {
	*x = GetCookieRequest{}
	mi := &file_proto_asset_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCookieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCookieRequest) ProtoMessage() {}

func (x *GetCookieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCookieRequest.ProtoReflect.Descriptor instead.
func (*GetCookieRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{29}
}

func (x *GetCookieRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCookieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cookie        *CookieInfo            `protobuf:"bytes,1,opt,name=cookie,proto3" json:"cookie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCookieResponse) Reset() {
	*x = GetCookieResponse{}
	mi := &file_proto_asset_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCookieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCookieResponse) ProtoMessage() {}

func (x *GetCookieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCookieResponse.ProtoReflect.Descriptor instead.
func (*GetCookieResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{30}
}

func (x *GetCookieResponse) GetCookie() *CookieInfo {
	if x != nil {
		return x.Cookie
	}
	return nil
}

type ListCookiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCookiesRequest) Reset() {
	*x = ListCookiesRequest{}
	mi := &file_proto_asset_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCookiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCookiesRequest) ProtoMessage() {}

func (x *ListCookiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCookiesRequest.ProtoReflect.Descriptor instead.
func (*ListCookiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{31}
}

func (x *ListCookiesRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ListCookiesRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListCookiesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCookiesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListCookiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Items         []*CookieInfo          `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCookiesResponse) Reset() {
	*x = ListCookiesResponse{}
	mi := &file_proto_asset_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCookiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCookiesResponse) ProtoMessage() {}

func (x *ListCookiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCookiesResponse.ProtoReflect.Descriptor instead.
func (*ListCookiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{32}
}

func (x *ListCookiesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListCookiesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCookiesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCookiesResponse) GetItems() []*CookieInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type FreezeCookieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CookieId      int64                  `protobuf:"varint,1,opt,name=cookie_id,json=cookieId,proto3" json:"cookie_id,omitempty"`
	FreezeSeconds int32                  `protobuf:"varint,2,opt,name=freeze_seconds,json=freezeSeconds,proto3" json:"freeze_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreezeCookieRequest) Reset() {
	*x = FreezeCookieRequest{}
	mi := &file_proto_asset_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreezeCookieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeCookieRequest) ProtoMessage() {}

func (x *FreezeCookieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeCookieRequest.ProtoReflect.Descriptor instead.
func (*FreezeCookieRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{33}
}

func (x *FreezeCookieRequest) GetCookieId() int64 {
	if x != nil {
		return x.CookieId
	}
	return 0
}

func (x *FreezeCookieRequest) GetFreezeSeconds() int32 {
	if x != nil {
		return x.FreezeSeconds
	}
	return 0
}

type FreezeCookieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	FrozenUntil   string                 `protobuf:"bytes,2,opt,name=frozen_until,json=frozenUntil,proto3" json:"frozen_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreezeCookieResponse) Reset() {
	*x = FreezeCookieResponse{}
	mi := &file_proto_asset_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreezeCookieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeCookieResponse) ProtoMessage() {}

func (x *FreezeCookieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeCookieResponse.ProtoReflect.Descriptor instead.
func (*FreezeCookieResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{34}
}

func (x *FreezeCookieResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FreezeCookieResponse) GetFrozenUntil() string {
	if x != nil {
		return x.FrozenUntil
	}
	return ""
}

var File_proto_asset_proto protoreflect.FileDescriptor

const file_proto_asset_proto_rawDesc = "" +
	"\n" +
	"\x11proto/asset.proto\x12\x05asset\"\x19\n" +
	"\x17GetPlatformStatsRequest\"\xa2\x02\n" +
	"\x18GetPlatformStatsResponse\x12'\n" +
	"\x0ftotal_downloads\x18\x01 \x01(\x03R\x0etotalDownloads\x12+\n" +
	"\x11success_downloads\x18\x02 \x01(\x03R\x10successDownloads\x12)\n" +
	"\x10failed_downloads\x18\x03 \x01(\x03R\x0ffailedDownloads\x12'\n" +
	"\x0fdownloads_today\x18\x04 \x01(\x03R\x0edownloadsToday\x12,\n" +
	"\x12daily_active_users\x18\x05 \x01(\x03R\x10dailyActiveUsers\x12.\n" +
	"\x13weekly_active_users\x18\x06 \x01(\x03R\x11weeklyActiveUsers\"P\n" +
	"\x16GetRequestTrendRequest\x12 \n" +
	"\vgranularity\x18\x01 \x01(\tR\vgranularity\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"8\n" +
	"\n" +
	"TrendPoint\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"f\n" +
	"\x17GetRequestTrendResponse\x12 \n" +
	"\vgranularity\x18\x01 \x01(\tR\vgranularity\x12)\n" +
	"\x06points\x18\x02 \x03(\v2\x11.asset.TrendPointR\x06points\"N\n" +
	"\x18GetAvailableProxyRequest\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\"{\n" +
	"\x19GetAvailableProxyResponse\x12\x1b\n" +
	"\tproxy_url\x18\x01 \x01(\tR\bproxyUrl\x12$\n" +
	"\x0eproxy_lease_id\x18\x02 \x01(\tR\fproxyLeaseId\x12\x1b\n" +
	"\texpire_at\x18\x03 \x01(\tR\bexpireAt\"\x1d\n" +
	"\x1bGetProxySourcePolicyRequest\"\xed\x03\n" +
	"\x1cGetProxySourcePolicyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"scope_type\x18\x02 \x01(\tR\tscopeType\x12\x1f\n" +
	"\vscope_value\x18\x03 \x01(\tR\n" +
	"scopeValue\x12%\n" +
	"\x0eprimary_source\x18\x04 \x01(\tR\rprimarySource\x12'\n" +
	"\x0ffallback_source\x18\x05 \x01(\tR\x0efallbackSource\x12)\n" +
	"\x10fallback_enabled\x18\x06 \x01(\bR\x0ffallbackEnabled\x12,\n" +
	"\x12dynamic_timeout_ms\x18\a \x01(\x05R\x10dynamicTimeoutMs\x12.\n" +
	"\x13dynamic_retry_count\x18\b \x01(\x05R\x11dynamicRetryCount\x12=\n" +
	"\x1bdynamic_circuit_breaker_sec\x18\t \x01(\x05R\x18dynamicCircuitBreakerSec\x12)\n" +
	"\x11min_lease_ttl_sec\x18\n" +
	" \x01(\x05R\x0eminLeaseTtlSec\x12:\n" +
	"\x19manual_selection_strategy\x18\v \x01(\tR\x17manualSelectionStrategy\"\xaf\x03\n" +
	"\x1eUpdateProxySourcePolicyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x0eprimary_source\x18\x02 \x01(\tR\rprimarySource\x12'\n" +
	"\x0ffallback_source\x18\x03 \x01(\tR\x0efallbackSource\x12)\n" +
	"\x10fallback_enabled\x18\x04 \x01(\bR\x0ffallbackEnabled\x12,\n" +
	"\x12dynamic_timeout_ms\x18\x05 \x01(\x05R\x10dynamicTimeoutMs\x12.\n" +
	"\x13dynamic_retry_count\x18\x06 \x01(\x05R\x11dynamicRetryCount\x12=\n" +
	"\x1bdynamic_circuit_breaker_sec\x18\a \x01(\x05R\x18dynamicCircuitBreakerSec\x12)\n" +
	"\x11min_lease_ttl_sec\x18\b \x01(\x05R\x0eminLeaseTtlSec\x12:\n" +
	"\x19manual_selection_strategy\x18\t \x01(\tR\x17manualSelectionStrategy\";\n" +
	"\x1fUpdateProxySourcePolicyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa8\x03\n" +
	"\tProxyInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12#\n" +
	"\rplatform_tags\x18\b \x01(\tR\fplatformTags\x12\x16\n" +
	"\x06remark\x18\t \x01(\tR\x06remark\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12 \n" +
	"\flast_used_at\x18\v \x01(\tR\n" +
	"lastUsedAt\x12#\n" +
	"\rsuccess_count\x18\f \x01(\x05R\fsuccessCount\x12\x1d\n" +
	"\n" +
	"fail_count\x18\r \x01(\x05R\tfailCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAt\"x\n" +
	"\x12ListProxiesRequest\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"=\n" +
	"\x13ListProxiesResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.asset.ProxyInfoR\x05items\"\x99\x02\n" +
	"\x12CreateProxyRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12#\n" +
	"\rplatform_tags\x18\b \x01(\tR\fplatformTags\x12\x16\n" +
	"\x06remark\x18\t \x01(\tR\x06remark\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\"%\n" +
	"\x13CreateProxyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x91\x02\n" +
	"\x12UpdateProxyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12\x16\n" +
	"\x06region\x18\a \x01(\tR\x06region\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriority\x12#\n" +
	"\rplatform_tags\x18\t \x01(\tR\fplatformTags\x12\x16\n" +
	"\x06remark\x18\n" +
	" \x01(\tR\x06remark\"/\n" +
	"\x13UpdateProxyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"B\n" +
	"\x18UpdateProxyStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"5\n" +
	"\x19UpdateProxyStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"$\n" +
	"\x12DeleteProxyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"/\n" +
	"\x13DeleteProxyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa6\x03\n" +
	"\n" +
	"CookieInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1b\n" +
	"\texpire_at\x18\x06 \x01(\tR\bexpireAt\x12!\n" +
	"\ffrozen_until\x18\a \x01(\tR\vfrozenUntil\x12%\n" +
	"\x0efreeze_seconds\x18\b \x01(\x05R\rfreezeSeconds\x12 \n" +
	"\flast_used_at\x18\t \x01(\tR\n" +
	"lastUsedAt\x12\x1b\n" +
	"\tuse_count\x18\n" +
	" \x01(\x05R\buseCount\x12#\n" +
	"\rsuccess_count\x18\v \x01(\x05R\fsuccessCount\x12\x1d\n" +
	"\n" +
	"fail_count\x18\f \x01(\x05R\tfailCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\"\xa3\x01\n" +
	"\x13CreateCookieRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\texpire_at\x18\x04 \x01(\tR\bexpireAt\x12%\n" +
	"\x0efreeze_seconds\x18\x05 \x01(\x05R\rfreezeSeconds\"&\n" +
	"\x14CreateCookieResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x97\x01\n" +
	"\x13UpdateCookieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\texpire_at\x18\x04 \x01(\tR\bexpireAt\x12%\n" +
	"\x0efreeze_seconds\x18\x05 \x01(\x05R\rfreezeSeconds\"0\n" +
	"\x14UpdateCookieResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"%\n" +
	"\x13DeleteCookieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"0\n" +
	"\x14DeleteCookieResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\"\n" +
	"\x10GetCookieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\">\n" +
	"\x11GetCookieResponse\x12)\n" +
	"\x06cookie\x18\x01 \x01(\v2\x11.asset.CookieInfoR\x06cookie\"y\n" +
	"\x12ListCookiesRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x85\x01\n" +
	"\x13ListCookiesResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12'\n" +
	"\x05items\x18\x04 \x03(\v2\x11.asset.CookieInfoR\x05items\"Y\n" +
	"\x13FreezeCookieRequest\x12\x1b\n" +
	"\tcookie_id\x18\x01 \x01(\x03R\bcookieId\x12%\n" +
	"\x0efreeze_seconds\x18\x02 \x01(\x05R\rfreezeSeconds\"S\n" +
	"\x14FreezeCookieResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\ffrozen_until\x18\x02 \x01(\tR\vfrozenUntil2\xf2\t\n" +
	"\fAssetService\x12S\n" +
	"\x10GetPlatformStats\x12\x1e.asset.GetPlatformStatsRequest\x1a\x1f.asset.GetPlatformStatsResponse\x12P\n" +
	"\x0fGetRequestTrend\x12\x1d.asset.GetRequestTrendRequest\x1a\x1e.asset.GetRequestTrendResponse\x12V\n" +
	"\x11GetAvailableProxy\x12\x1f.asset.GetAvailableProxyRequest\x1a .asset.GetAvailableProxyResponse\x12_\n" +
	"\x14GetProxySourcePolicy\x12\".asset.GetProxySourcePolicyRequest\x1a#.asset.GetProxySourcePolicyResponse\x12h\n" +
	"\x17UpdateProxySourcePolicy\x12%.asset.UpdateProxySourcePolicyRequest\x1a&.asset.UpdateProxySourcePolicyResponse\x12D\n" +
	"\vListProxies\x12\x19.asset.ListProxiesRequest\x1a\x1a.asset.ListProxiesResponse\x12D\n" +
	"\vCreateProxy\x12\x19.asset.CreateProxyRequest\x1a\x1a.asset.CreateProxyResponse\x12D\n" +
	"\vUpdateProxy\x12\x19.asset.UpdateProxyRequest\x1a\x1a.asset.UpdateProxyResponse\x12V\n" +
	"\x11UpdateProxyStatus\x12\x1f.asset.UpdateProxyStatusRequest\x1a .asset.UpdateProxyStatusResponse\x12D\n" +
	"\vDeleteProxy\x12\x19.asset.DeleteProxyRequest\x1a\x1a.asset.DeleteProxyResponse\x12G\n" +
	"\fCreateCookie\x12\x1a.asset.CreateCookieRequest\x1a\x1b.asset.CreateCookieResponse\x12G\n" +
	"\fUpdateCookie\x12\x1a.asset.UpdateCookieRequest\x1a\x1b.asset.UpdateCookieResponse\x12G\n" +
	"\fDeleteCookie\x12\x1a.asset.DeleteCookieRequest\x1a\x1b.asset.DeleteCookieResponse\x12>\n" +
	"\tGetCookie\x12\x17.asset.GetCookieRequest\x1a\x18.asset.GetCookieResponse\x12D\n" +
	"\vListCookies\x12\x19.asset.ListCookiesRequest\x1a\x1a.asset.ListCookiesResponse\x12G\n" +
	"\fFreezeCookie\x12\x1a.asset.FreezeCookieRequest\x1a\x1b.asset.FreezeCookieResponseB\x1fZ\x1dvasset/admin-service/proto;pbb\x06proto3"

var (
	file_proto_asset_proto_rawDescOnce sync.Once
	file_proto_asset_proto_rawDescData []byte
)

func file_proto_asset_proto_rawDescGZIP() []byte {
	file_proto_asset_proto_rawDescOnce.Do(func() {
		file_proto_asset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_asset_proto_rawDesc), len(file_proto_asset_proto_rawDesc)))
	})
	return file_proto_asset_proto_rawDescData
}

var file_proto_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_proto_asset_proto_goTypes = []any{
	(*GetPlatformStatsRequest)(nil),         // 0: asset.GetPlatformStatsRequest
	(*GetPlatformStatsResponse)(nil),        // 1: asset.GetPlatformStatsResponse
	(*GetRequestTrendRequest)(nil),          // 2: asset.GetRequestTrendRequest
	(*TrendPoint)(nil),                      // 3: asset.TrendPoint
	(*GetRequestTrendResponse)(nil),         // 4: asset.GetRequestTrendResponse
	(*GetAvailableProxyRequest)(nil),        // 5: asset.GetAvailableProxyRequest
	(*GetAvailableProxyResponse)(nil),       // 6: asset.GetAvailableProxyResponse
	(*GetProxySourcePolicyRequest)(nil),     // 7: asset.GetProxySourcePolicyRequest
	(*GetProxySourcePolicyResponse)(nil),    // 8: asset.GetProxySourcePolicyResponse
	(*UpdateProxySourcePolicyRequest)(nil),  // 9: asset.UpdateProxySourcePolicyRequest
	(*UpdateProxySourcePolicyResponse)(nil), // 10: asset.UpdateProxySourcePolicyResponse
	(*ProxyInfo)(nil),                       // 11: asset.ProxyInfo
	(*ListProxiesRequest)(nil),              // 12: asset.ListProxiesRequest
	(*ListProxiesResponse)(nil),             // 13: asset.ListProxiesResponse
	(*CreateProxyRequest)(nil),              // 14: asset.CreateProxyRequest
	(*CreateProxyResponse)(nil),             // 15: asset.CreateProxyResponse
	(*UpdateProxyRequest)(nil),              // 16: asset.UpdateProxyRequest
	(*UpdateProxyResponse)(nil),             // 17: asset.UpdateProxyResponse
	(*UpdateProxyStatusRequest)(nil),        // 18: asset.UpdateProxyStatusRequest
	(*UpdateProxyStatusResponse)(nil),       // 19: asset.UpdateProxyStatusResponse
	(*DeleteProxyRequest)(nil),              // 20: asset.DeleteProxyRequest
	(*DeleteProxyResponse)(nil),             // 21: asset.DeleteProxyResponse
	(*CookieInfo)(nil),                      // 22: asset.CookieInfo
	(*CreateCookieRequest)(nil),             // 23: asset.CreateCookieRequest
	(*CreateCookieResponse)(nil),            // 24: asset.CreateCookieResponse
	(*UpdateCookieRequest)(nil),             // 25: asset.UpdateCookieRequest
	(*UpdateCookieResponse)(nil),            // 26: asset.UpdateCookieResponse
	(*DeleteCookieRequest)(nil),             // 27: asset.DeleteCookieRequest
	(*DeleteCookieResponse)(nil),            // 28: asset.DeleteCookieResponse
	(*GetCookieRequest)(nil),                // 29: asset.GetCookieRequest
	(*GetCookieResponse)(nil),               // 30: asset.GetCookieResponse
	(*ListCookiesRequest)(nil),              // 31: asset.ListCookiesRequest
	(*ListCookiesResponse)(nil),             // 32: asset.ListCookiesResponse
	(*FreezeCookieRequest)(nil),             // 33: asset.FreezeCookieRequest
	(*FreezeCookieResponse)(nil),            // 34: asset.FreezeCookieResponse
}
var file_proto_asset_proto_depIdxs = []int32{
	3,  // 0: asset.GetRequestTrendResponse.points:type_name -> asset.TrendPoint
	11, // 1: asset.ListProxiesResponse.items:type_name -> asset.ProxyInfo
	22, // 2: asset.GetCookieResponse.cookie:type_name -> asset.CookieInfo
	22, // 3: asset.ListCookiesResponse.items:type_name -> asset.CookieInfo
	0,  // 4: asset.AssetService.GetPlatformStats:input_type -> asset.GetPlatformStatsRequest
	2,  // 5: asset.AssetService.GetRequestTrend:input_type -> asset.GetRequestTrendRequest
	5,  // 6: asset.AssetService.GetAvailableProxy:input_type -> asset.GetAvailableProxyRequest
	7,  // 7: asset.AssetService.GetProxySourcePolicy:input_type -> asset.GetProxySourcePolicyRequest
	9,  // 8: asset.AssetService.UpdateProxySourcePolicy:input_type -> asset.UpdateProxySourcePolicyRequest
	12, // 9: asset.AssetService.ListProxies:input_type -> asset.ListProxiesRequest
	14, // 10: asset.AssetService.CreateProxy:input_type -> asset.CreateProxyRequest
	16, // 11: asset.AssetService.UpdateProxy:input_type -> asset.UpdateProxyRequest
	18, // 12: asset.AssetService.UpdateProxyStatus:input_type -> asset.UpdateProxyStatusRequest
	20, // 13: asset.AssetService.DeleteProxy:input_type -> asset.DeleteProxyRequest
	23, // 14: asset.AssetService.CreateCookie:input_type -> asset.CreateCookieRequest
	25, // 15: asset.AssetService.UpdateCookie:input_type -> asset.UpdateCookieRequest
	27, // 16: asset.AssetService.DeleteCookie:input_type -> asset.DeleteCookieRequest
	29, // 17: asset.AssetService.GetCookie:input_type -> asset.GetCookieRequest
	31, // 18: asset.AssetService.ListCookies:input_type -> asset.ListCookiesRequest
	33, // 19: asset.AssetService.FreezeCookie:input_type -> asset.FreezeCookieRequest
	1,  // 20: asset.AssetService.GetPlatformStats:output_type -> asset.GetPlatformStatsResponse
	4,  // 21: asset.AssetService.GetRequestTrend:output_type -> asset.GetRequestTrendResponse
	6,  // 22: asset.AssetService.GetAvailableProxy:output_type -> asset.GetAvailableProxyResponse
	8,  // 23: asset.AssetService.GetProxySourcePolicy:output_type -> asset.GetProxySourcePolicyResponse
	10, // 24: asset.AssetService.UpdateProxySourcePolicy:output_type -> asset.UpdateProxySourcePolicyResponse
	13, // 25: asset.AssetService.ListProxies:output_type -> asset.ListProxiesResponse
	15, // 26: asset.AssetService.CreateProxy:output_type -> asset.CreateProxyResponse
	17, // 27: asset.AssetService.UpdateProxy:output_type -> asset.UpdateProxyResponse
	19, // 28: asset.AssetService.UpdateProxyStatus:output_type -> asset.UpdateProxyStatusResponse
	21, // 29: asset.AssetService.DeleteProxy:output_type -> asset.DeleteProxyResponse
	24, // 30: asset.AssetService.CreateCookie:output_type -> asset.CreateCookieResponse
	26, // 31: asset.AssetService.UpdateCookie:output_type -> asset.UpdateCookieResponse
	28, // 32: asset.AssetService.DeleteCookie:output_type -> asset.DeleteCookieResponse
	30, // 33: asset.AssetService.GetCookie:output_type -> asset.GetCookieResponse
	32, // 34: asset.AssetService.ListCookies:output_type -> asset.ListCookiesResponse
	34, // 35: asset.AssetService.FreezeCookie:output_type -> asset.FreezeCookieResponse
	20, // [20:36] is the sub-list for method output_type
	4,  // [4:20] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_asset_proto_init() }
func file_proto_asset_proto_init() {
	if File_proto_asset_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_asset_proto_rawDesc), len(file_proto_asset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_asset_proto_goTypes,
		DependencyIndexes: file_proto_asset_proto_depIdxs,
		MessageInfos:      file_proto_asset_proto_msgTypes,
	}.Build()
	File_proto_asset_proto = out.File
	file_proto_asset_proto_goTypes = nil
	file_proto_asset_proto_depIdxs = nil
}
