// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/asset.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssetService_GetPlatformStats_FullMethodName        = "/asset.AssetService/GetPlatformStats"
	AssetService_GetRequestTrend_FullMethodName         = "/asset.AssetService/GetRequestTrend"
	AssetService_GetAvailableProxy_FullMethodName       = "/asset.AssetService/GetAvailableProxy"
	AssetService_GetProxySourcePolicy_FullMethodName    = "/asset.AssetService/GetProxySourcePolicy"
	AssetService_UpdateProxySourcePolicy_FullMethodName = "/asset.AssetService/UpdateProxySourcePolicy"
	AssetService_ListProxies_FullMethodName             = "/asset.AssetService/ListProxies"
	AssetService_CreateProxy_FullMethodName             = "/asset.AssetService/CreateProxy"
	AssetService_UpdateProxy_FullMethodName             = "/asset.AssetService/UpdateProxy"
	AssetService_UpdateProxyStatus_FullMethodName       = "/asset.AssetService/UpdateProxyStatus"
	AssetService_DeleteProxy_FullMethodName             = "/asset.AssetService/DeleteProxy"
	AssetService_CreateCookie_FullMethodName            = "/asset.AssetService/CreateCookie"
	AssetService_UpdateCookie_FullMethodName            = "/asset.AssetService/UpdateCookie"
	AssetService_DeleteCookie_FullMethodName            = "/asset.AssetService/DeleteCookie"
	AssetService_GetCookie_FullMethodName               = "/asset.AssetService/GetCookie"
	AssetService_ListCookies_FullMethodName             = "/asset.AssetService/ListCookies"
	AssetService_FreezeCookie_FullMethodName            = "/asset.AssetService/FreezeCookie"
)

// AssetServiceClient is the client API for AssetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssetServiceClient interface {
	GetPlatformStats(ctx context.Context, in *GetPlatformStatsRequest, opts ...grpc.CallOption) (*GetPlatformStatsResponse, error)
	GetRequestTrend(ctx context.Context, in *GetRequestTrendRequest, opts ...grpc.CallOption) (*GetRequestTrendResponse, error)
	GetAvailableProxy(ctx context.Context, in *GetAvailableProxyRequest, opts ...grpc.CallOption) (*GetAvailableProxyResponse, error)
	GetProxySourcePolicy(ctx context.Context, in *GetProxySourcePolicyRequest, opts ...grpc.CallOption) (*GetProxySourcePolicyResponse, error)
	UpdateProxySourcePolicy(ctx context.Context, in *UpdateProxySourcePolicyRequest, opts ...grpc.CallOption) (*UpdateProxySourcePolicyResponse, error)
	ListProxies(ctx context.Context, in *ListProxiesRequest, opts ...grpc.CallOption) (*ListProxiesResponse, error)
	CreateProxy(ctx context.Context, in *CreateProxyRequest, opts ...grpc.CallOption) (*CreateProxyResponse, error)
	UpdateProxy(ctx context.Context, in *UpdateProxyRequest, opts ...grpc.CallOption) (*UpdateProxyResponse, error)
	UpdateProxyStatus(ctx context.Context, in *UpdateProxyStatusRequest, opts ...grpc.CallOption) (*UpdateProxyStatusResponse, error)
	DeleteProxy(ctx context.Context, in *DeleteProxyRequest, opts ...grpc.CallOption) (*DeleteProxyResponse, error)
	CreateCookie(ctx context.Context, in *CreateCookieRequest, opts ...grpc.CallOption) (*CreateCookieResponse, error)
	UpdateCookie(ctx context.Context, in *UpdateCookieRequest, opts ...grpc.CallOption) (*UpdateCookieResponse, error)
	DeleteCookie(ctx context.Context, in *DeleteCookieRequest, opts ...grpc.CallOption) (*DeleteCookieResponse, error)
	GetCookie(ctx context.Context, in *GetCookieRequest, opts ...grpc.CallOption) (*GetCookieResponse, error)
	ListCookies(ctx context.Context, in *ListCookiesRequest, opts ...grpc.CallOption) (*ListCookiesResponse, error)
	FreezeCookie(ctx context.Context, in *FreezeCookieRequest, opts ...grpc.CallOption) (*FreezeCookieResponse, error)
}

type assetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetServiceClient(cc grpc.ClientConnInterface) AssetServiceClient {
	return &assetServiceClient{cc}
}

func (c *assetServiceClient) GetPlatformStats(ctx context.Context, in *GetPlatformStatsRequest, opts ...grpc.CallOption) (*GetPlatformStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlatformStatsResponse)
	err := c.cc.Invoke(ctx, AssetService_GetPlatformStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) GetRequestTrend(ctx context.Context, in *GetRequestTrendRequest, opts ...grpc.CallOption) (*GetRequestTrendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRequestTrendResponse)
	err := c.cc.Invoke(ctx, AssetService_GetRequestTrend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) GetAvailableProxy(ctx context.Context, in *GetAvailableProxyRequest, opts ...grpc.CallOption) (*GetAvailableProxyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableProxyResponse)
	err := c.cc.Invoke(ctx, AssetService_GetAvailableProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) GetProxySourcePolicy(ctx context.Context, in *GetProxySourcePolicyRequest, opts ...grpc.CallOption) (*GetProxySourcePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProxySourcePolicyResponse)
	err := c.cc.Invoke(ctx, AssetService_GetProxySourcePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) UpdateProxySourcePolicy(ctx context.Context, in *UpdateProxySourcePolicyRequest, opts ...grpc.CallOption) (*UpdateProxySourcePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProxySourcePolicyResponse)
	err := c.cc.Invoke(ctx, AssetService_UpdateProxySourcePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) ListProxies(ctx context.Context, in *ListProxiesRequest, opts ...grpc.CallOption) (*ListProxiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProxiesResponse)
	err := c.cc.Invoke(ctx, AssetService_ListProxies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) CreateProxy(ctx context.Context, in *CreateProxyRequest, opts ...grpc.CallOption) (*CreateProxyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProxyResponse)
	err := c.cc.Invoke(ctx, AssetService_CreateProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) UpdateProxy(ctx context.Context, in *UpdateProxyRequest, opts ...grpc.CallOption) (*UpdateProxyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProxyResponse)
	err := c.cc.Invoke(ctx, AssetService_UpdateProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) UpdateProxyStatus(ctx context.Context, in *UpdateProxyStatusRequest, opts ...grpc.CallOption) (*UpdateProxyStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProxyStatusResponse)
	err := c.cc.Invoke(ctx, AssetService_UpdateProxyStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) DeleteProxy(ctx context.Context, in *DeleteProxyRequest, opts ...grpc.CallOption) (*DeleteProxyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProxyResponse)
	err := c.cc.Invoke(ctx, AssetService_DeleteProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) CreateCookie(ctx context.Context, in *CreateCookieRequest, opts ...grpc.CallOption) (*CreateCookieResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCookieResponse)
	err := c.cc.Invoke(ctx, AssetService_CreateCookie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) UpdateCookie(ctx context.Context, in *UpdateCookieRequest, opts ...grpc.CallOption) (*UpdateCookieResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCookieResponse)
	err := c.cc.Invoke(ctx, AssetService_UpdateCookie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) DeleteCookie(ctx context.Context, in *DeleteCookieRequest, opts ...grpc.CallOption) (*DeleteCookieResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCookieResponse)
	err := c.cc.Invoke(ctx, AssetService_DeleteCookie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) GetCookie(ctx context.Context, in *GetCookieRequest, opts ...grpc.CallOption) (*GetCookieResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCookieResponse)
	err := c.cc.Invoke(ctx, AssetService_GetCookie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) ListCookies(ctx context.Context, in *ListCookiesRequest, opts ...grpc.CallOption) (*ListCookiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCookiesResponse)
	err := c.cc.Invoke(ctx, AssetService_ListCookies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) FreezeCookie(ctx context.Context, in *FreezeCookieRequest, opts ...grpc.CallOption) (*FreezeCookieResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FreezeCookieResponse)
	err := c.cc.Invoke(ctx, AssetService_FreezeCookie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetServiceServer is the server API for AssetService service.
// All implementations must embed UnimplementedAssetServiceServer
// for forward compatibility.
type AssetServiceServer interface {
	GetPlatformStats(context.Context, *GetPlatformStatsRequest) (*GetPlatformStatsResponse, error)
	GetRequestTrend(context.Context, *GetRequestTrendRequest) (*GetRequestTrendResponse, error)
	GetAvailableProxy(context.Context, *GetAvailableProxyRequest) (*GetAvailableProxyResponse, error)
	GetProxySourcePolicy(context.Context, *GetProxySourcePolicyRequest) (*GetProxySourcePolicyResponse, error)
	UpdateProxySourcePolicy(context.Context, *UpdateProxySourcePolicyRequest) (*UpdateProxySourcePolicyResponse, error)
	ListProxies(context.Context, *ListProxiesRequest) (*ListProxiesResponse, error)
	CreateProxy(context.Context, *CreateProxyRequest) (*CreateProxyResponse, error)
	UpdateProxy(context.Context, *UpdateProxyRequest) (*UpdateProxyResponse, error)
	UpdateProxyStatus(context.Context, *UpdateProxyStatusRequest) (*UpdateProxyStatusResponse, error)
	DeleteProxy(context.Context, *DeleteProxyRequest) (*DeleteProxyResponse, error)
	CreateCookie(context.Context, *CreateCookieRequest) (*CreateCookieResponse, error)
	UpdateCookie(context.Context, *UpdateCookieRequest) (*UpdateCookieResponse, error)
	DeleteCookie(context.Context, *DeleteCookieRequest) (*DeleteCookieResponse, error)
	GetCookie(context.Context, *GetCookieRequest) (*GetCookieResponse, error)
	ListCookies(context.Context, *ListCookiesRequest) (*ListCookiesResponse, error)
	FreezeCookie(context.Context, *FreezeCookieRequest) (*FreezeCookieResponse, error)
	mustEmbedUnimplementedAssetServiceServer()
}

// UnimplementedAssetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssetServiceServer struct{}

func (UnimplementedAssetServiceServer) GetPlatformStats(context.Context, *GetPlatformStatsRequest) (*GetPlatformStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlatformStats not implemented")
}
func (UnimplementedAssetServiceServer) GetRequestTrend(context.Context, *GetRequestTrendRequest) (*GetRequestTrendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRequestTrend not implemented")
}
func (UnimplementedAssetServiceServer) GetAvailableProxy(context.Context, *GetAvailableProxyRequest) (*GetAvailableProxyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableProxy not implemented")
}
func (UnimplementedAssetServiceServer) GetProxySourcePolicy(context.Context, *GetProxySourcePolicyRequest) (*GetProxySourcePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProxySourcePolicy not implemented")
}
func (UnimplementedAssetServiceServer) UpdateProxySourcePolicy(context.Context, *UpdateProxySourcePolicyRequest) (*UpdateProxySourcePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProxySourcePolicy not implemented")
}
func (UnimplementedAssetServiceServer) ListProxies(context.Context, *ListProxiesRequest) (*ListProxiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProxies not implemented")
}
func (UnimplementedAssetServiceServer) CreateProxy(context.Context, *CreateProxyRequest) (*CreateProxyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProxy not implemented")
}
func (UnimplementedAssetServiceServer) UpdateProxy(context.Context, *UpdateProxyRequest) (*UpdateProxyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProxy not implemented")
}
func (UnimplementedAssetServiceServer) UpdateProxyStatus(context.Context, *UpdateProxyStatusRequest) (*UpdateProxyStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProxyStatus not implemented")
}
func (UnimplementedAssetServiceServer) DeleteProxy(context.Context, *DeleteProxyRequest) (*DeleteProxyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProxy not implemented")
}
func (UnimplementedAssetServiceServer) CreateCookie(context.Context, *CreateCookieRequest) (*CreateCookieResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCookie not implemented")
}
func (UnimplementedAssetServiceServer) UpdateCookie(context.Context, *UpdateCookieRequest) (*UpdateCookieResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCookie not implemented")
}
func (UnimplementedAssetServiceServer) DeleteCookie(context.Context, *DeleteCookieRequest) (*DeleteCookieResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCookie not implemented")
}
func (UnimplementedAssetServiceServer) GetCookie(context.Context, *GetCookieRequest) (*GetCookieResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCookie not implemented")
}
func (UnimplementedAssetServiceServer) ListCookies(context.Context, *ListCookiesRequest) (*ListCookiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCookies not implemented")
}
func (UnimplementedAssetServiceServer) FreezeCookie(context.Context, *FreezeCookieRequest) (*FreezeCookieResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FreezeCookie not implemented")
}
func (UnimplementedAssetServiceServer) mustEmbedUnimplementedAssetServiceServer() {}
func (UnimplementedAssetServiceServer) testEmbeddedByValue()                      {}

// UnsafeAssetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetServiceServer will
// result in compilation errors.
type UnsafeAssetServiceServer interface {
	mustEmbedUnimplementedAssetServiceServer()
}

func RegisterAssetServiceServer(s grpc.ServiceRegistrar, srv AssetServiceServer) {
	// If the following call panics, it indicates UnimplementedAssetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssetService_ServiceDesc, srv)
}

func _AssetService_GetPlatformStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlatformStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).GetPlatformStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_GetPlatformStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).GetPlatformStats(ctx, req.(*GetPlatformStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_GetRequestTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequestTrendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).GetRequestTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_GetRequestTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).GetRequestTrend(ctx, req.(*GetRequestTrendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_GetAvailableProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).GetAvailableProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_GetAvailableProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).GetAvailableProxy(ctx, req.(*GetAvailableProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_GetProxySourcePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProxySourcePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).GetProxySourcePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_GetProxySourcePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).GetProxySourcePolicy(ctx, req.(*GetProxySourcePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_UpdateProxySourcePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProxySourcePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).UpdateProxySourcePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_UpdateProxySourcePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).UpdateProxySourcePolicy(ctx, req.(*UpdateProxySourcePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_ListProxies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProxiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).ListProxies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_ListProxies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).ListProxies(ctx, req.(*ListProxiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_CreateProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).CreateProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_CreateProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).CreateProxy(ctx, req.(*CreateProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_UpdateProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).UpdateProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_UpdateProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).UpdateProxy(ctx, req.(*UpdateProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_UpdateProxyStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProxyStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).UpdateProxyStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_UpdateProxyStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).UpdateProxyStatus(ctx, req.(*UpdateProxyStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_DeleteProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).DeleteProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_DeleteProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).DeleteProxy(ctx, req.(*DeleteProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_CreateCookie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCookieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).CreateCookie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_CreateCookie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).CreateCookie(ctx, req.(*CreateCookieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_UpdateCookie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCookieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).UpdateCookie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_UpdateCookie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).UpdateCookie(ctx, req.(*UpdateCookieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_DeleteCookie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCookieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).DeleteCookie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_DeleteCookie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).DeleteCookie(ctx, req.(*DeleteCookieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_GetCookie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCookieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).GetCookie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_GetCookie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).GetCookie(ctx, req.(*GetCookieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_ListCookies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCookiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).ListCookies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_ListCookies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).ListCookies(ctx, req.(*ListCookiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_FreezeCookie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FreezeCookieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).FreezeCookie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_FreezeCookie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).FreezeCookie(ctx, req.(*FreezeCookieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetService_ServiceDesc is the grpc.ServiceDesc for AssetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "asset.AssetService",
	HandlerType: (*AssetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlatformStats",
			Handler:    _AssetService_GetPlatformStats_Handler,
		},
		{
			MethodName: "GetRequestTrend",
			Handler:    _AssetService_GetRequestTrend_Handler,
		},
		{
			MethodName: "GetAvailableProxy",
			Handler:    _AssetService_GetAvailableProxy_Handler,
		},
		{
			MethodName: "GetProxySourcePolicy",
			Handler:    _AssetService_GetProxySourcePolicy_Handler,
		},
		{
			MethodName: "UpdateProxySourcePolicy",
			Handler:    _AssetService_UpdateProxySourcePolicy_Handler,
		},
		{
			MethodName: "ListProxies",
			Handler:    _AssetService_ListProxies_Handler,
		},
		{
			MethodName: "CreateProxy",
			Handler:    _AssetService_CreateProxy_Handler,
		},
		{
			MethodName: "UpdateProxy",
			Handler:    _AssetService_UpdateProxy_Handler,
		},
		{
			MethodName: "UpdateProxyStatus",
			Handler:    _AssetService_UpdateProxyStatus_Handler,
		},
		{
			MethodName: "DeleteProxy",
			Handler:    _AssetService_DeleteProxy_Handler,
		},
		{
			MethodName: "CreateCookie",
			Handler:    _AssetService_CreateCookie_Handler,
		},
		{
			MethodName: "UpdateCookie",
			Handler:    _AssetService_UpdateCookie_Handler,
		},
		{
			MethodName: "DeleteCookie",
			Handler:    _AssetService_DeleteCookie_Handler,
		},
		{
			MethodName: "GetCookie",
			Handler:    _AssetService_GetCookie_Handler,
		},
		{
			MethodName: "ListCookies",
			Handler:    _AssetService_ListCookies_Handler,
		},
		{
			MethodName: "FreezeCookie",
			Handler:    _AssetService_FreezeCookie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/asset.proto",
}
