// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/admin.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_Login_FullMethodName                   = "/admin.AdminService/Login"
	AdminService_Logout_FullMethodName                  = "/admin.AdminService/Logout"
	AdminService_GetCurrentUser_FullMethodName          = "/admin.AdminService/GetCurrentUser"
	AdminService_GetOverview_FullMethodName             = "/admin.AdminService/GetOverview"
	AdminService_GetRequestTrend_FullMethodName         = "/admin.AdminService/GetRequestTrend"
	AdminService_GetUserStats_FullMethodName            = "/admin.AdminService/GetUserStats"
	AdminService_GetProxySourceStatus_FullMethodName    = "/admin.AdminService/GetProxySourceStatus"
	AdminService_GetProxySourcePolicy_FullMethodName    = "/admin.AdminService/GetProxySourcePolicy"
	AdminService_UpdateProxySourcePolicy_FullMethodName = "/admin.AdminService/UpdateProxySourcePolicy"
	AdminService_ListProxies_FullMethodName             = "/admin.AdminService/ListProxies"
	AdminService_CreateProxy_FullMethodName             = "/admin.AdminService/CreateProxy"
	AdminService_UpdateProxy_FullMethodName             = "/admin.AdminService/UpdateProxy"
	AdminService_UpdateProxyStatus_FullMethodName       = "/admin.AdminService/UpdateProxyStatus"
	AdminService_DeleteProxy_FullMethodName             = "/admin.AdminService/DeleteProxy"
	AdminService_ListCookies_FullMethodName             = "/admin.AdminService/ListCookies"
	AdminService_CreateCookie_FullMethodName            = "/admin.AdminService/CreateCookie"
	AdminService_UpdateCookie_FullMethodName            = "/admin.AdminService/UpdateCookie"
	AdminService_DeleteCookie_FullMethodName            = "/admin.AdminService/DeleteCookie"
	AdminService_FreezeCookie_FullMethodName            = "/admin.AdminService/FreezeCookie"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	Login(ctx context.Context, in *AdminLoginRequest, opts ...grpc.CallOption) (*AdminLoginResponse, error)
	Logout(ctx context.Context, in *AdminLogoutRequest, opts ...grpc.CallOption) (*AdminOperationResponse, error)
	GetCurrentUser(ctx context.Context, in *AdminSessionRequest, opts ...grpc.CallOption) (*AdminCurrentUserResponse, error)
	GetOverview(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*AdminOverviewResponse, error)
	GetRequestTrend(ctx context.Context, in *AdminRequestTrendRequest, opts ...grpc.CallOption) (*AdminRequestTrendResponse, error)
	GetUserStats(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*AdminUserStatsResponse, error)
	GetProxySourceStatus(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*AdminProxySourceStatusResponse, error)
	GetProxySourcePolicy(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*AdminProxySourcePolicyResponse, error)
	UpdateProxySourcePolicy(ctx context.Context, in *AdminUpdateProxySourcePolicyRequest, opts ...grpc.CallOption) (*AdminOperationResponse, error)
	ListProxies(ctx context.Context, in *AdminListProxiesRequest, opts ...grpc.CallOption) (*AdminListProxiesResponse, error)
	CreateProxy(ctx context.Context, in *AdminCreateProxyRequest, opts ...grpc.CallOption) (*AdminCreateResourceResponse, error)
	UpdateProxy(ctx context.Context, in *AdminUpdateProxyRequest, opts ...grpc.CallOption) (*AdminOperationResponse, error)
	UpdateProxyStatus(ctx context.Context, in *AdminUpdateProxyStatusRequest, opts ...grpc.CallOption) (*AdminOperationResponse, error)
	DeleteProxy(ctx context.Context, in *AdminDeleteRequest, opts ...grpc.CallOption) (*AdminOperationResponse, error)
	ListCookies(ctx context.Context, in *AdminListCookiesRequest, opts ...grpc.CallOption) (*AdminListCookiesResponse, error)
	CreateCookie(ctx context.Context, in *AdminCreateCookieRequest, opts ...grpc.CallOption) (*AdminCreateResourceResponse, error)
	UpdateCookie(ctx context.Context, in *AdminUpdateCookieRequest, opts ...grpc.CallOption) (*AdminOperationResponse, error)
	DeleteCookie(ctx context.Context, in *AdminDeleteRequest, opts ...grpc.CallOption) (*AdminOperationResponse, error)
	FreezeCookie(ctx context.Context, in *AdminFreezeCookieRequest, opts ...grpc.CallOption) (*AdminFreezeCookieResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) Login(ctx context.Context, in *AdminLoginRequest, opts ...grpc.CallOption) (*AdminLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminLoginResponse)
	err := c.cc.Invoke(ctx, AdminService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Logout(ctx context.Context, in *AdminLogoutRequest, opts ...grpc.CallOption) (*AdminOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminOperationResponse)
	err := c.cc.Invoke(ctx, AdminService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetCurrentUser(ctx context.Context, in *AdminSessionRequest, opts ...grpc.CallOption) (*AdminCurrentUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminCurrentUserResponse)
	err := c.cc.Invoke(ctx, AdminService_GetCurrentUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetOverview(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*AdminOverviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminOverviewResponse)
	err := c.cc.Invoke(ctx, AdminService_GetOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetRequestTrend(ctx context.Context, in *AdminRequestTrendRequest, opts ...grpc.CallOption) (*AdminRequestTrendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminRequestTrendResponse)
	err := c.cc.Invoke(ctx, AdminService_GetRequestTrend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetUserStats(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*AdminUserStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminUserStatsResponse)
	err := c.cc.Invoke(ctx, AdminService_GetUserStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetProxySourceStatus(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*AdminProxySourceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminProxySourceStatusResponse)
	err := c.cc.Invoke(ctx, AdminService_GetProxySourceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetProxySourcePolicy(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*AdminProxySourcePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminProxySourcePolicyResponse)
	err := c.cc.Invoke(ctx, AdminService_GetProxySourcePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpdateProxySourcePolicy(ctx context.Context, in *AdminUpdateProxySourcePolicyRequest, opts ...grpc.CallOption) (*AdminOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminOperationResponse)
	err := c.cc.Invoke(ctx, AdminService_UpdateProxySourcePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListProxies(ctx context.Context, in *AdminListProxiesRequest, opts ...grpc.CallOption) (*AdminListProxiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListProxiesResponse)
	err := c.cc.Invoke(ctx, AdminService_ListProxies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CreateProxy(ctx context.Context, in *AdminCreateProxyRequest, opts ...grpc.CallOption) (*AdminCreateResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminCreateResourceResponse)
	err := c.cc.Invoke(ctx, AdminService_CreateProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpdateProxy(ctx context.Context, in *AdminUpdateProxyRequest, opts ...grpc.CallOption) (*AdminOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminOperationResponse)
	err := c.cc.Invoke(ctx, AdminService_UpdateProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpdateProxyStatus(ctx context.Context, in *AdminUpdateProxyStatusRequest, opts ...grpc.CallOption) (*AdminOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminOperationResponse)
	err := c.cc.Invoke(ctx, AdminService_UpdateProxyStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeleteProxy(ctx context.Context, in *AdminDeleteRequest, opts ...grpc.CallOption) (*AdminOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminOperationResponse)
	err := c.cc.Invoke(ctx, AdminService_DeleteProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListCookies(ctx context.Context, in *AdminListCookiesRequest, opts ...grpc.CallOption) (*AdminListCookiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListCookiesResponse)
	err := c.cc.Invoke(ctx, AdminService_ListCookies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CreateCookie(ctx context.Context, in *AdminCreateCookieRequest, opts ...grpc.CallOption) (*AdminCreateResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminCreateResourceResponse)
	err := c.cc.Invoke(ctx, AdminService_CreateCookie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpdateCookie(ctx context.Context, in *AdminUpdateCookieRequest, opts ...grpc.CallOption) (*AdminOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminOperationResponse)
	err := c.cc.Invoke(ctx, AdminService_UpdateCookie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeleteCookie(ctx context.Context, in *AdminDeleteRequest, opts ...grpc.CallOption) (*AdminOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminOperationResponse)
	err := c.cc.Invoke(ctx, AdminService_DeleteCookie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) FreezeCookie(ctx context.Context, in *AdminFreezeCookieRequest, opts ...grpc.CallOption) (*AdminFreezeCookieResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminFreezeCookieResponse)
	err := c.cc.Invoke(ctx, AdminService_FreezeCookie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
type AdminServiceServer interface {
	Login(context.Context, *AdminLoginRequest) (*AdminLoginResponse, error)
	Logout(context.Context, *AdminLogoutRequest) (*AdminOperationResponse, error)
	GetCurrentUser(context.Context, *AdminSessionRequest) (*AdminCurrentUserResponse, error)
	GetOverview(context.Context, *AdminEmpty) (*AdminOverviewResponse, error)
	GetRequestTrend(context.Context, *AdminRequestTrendRequest) (*AdminRequestTrendResponse, error)
	GetUserStats(context.Context, *AdminEmpty) (*AdminUserStatsResponse, error)
	GetProxySourceStatus(context.Context, *AdminEmpty) (*AdminProxySourceStatusResponse, error)
	GetProxySourcePolicy(context.Context, *AdminEmpty) (*AdminProxySourcePolicyResponse, error)
	UpdateProxySourcePolicy(context.Context, *AdminUpdateProxySourcePolicyRequest) (*AdminOperationResponse, error)
	ListProxies(context.Context, *AdminListProxiesRequest) (*AdminListProxiesResponse, error)
	CreateProxy(context.Context, *AdminCreateProxyRequest) (*AdminCreateResourceResponse, error)
	UpdateProxy(context.Context, *AdminUpdateProxyRequest) (*AdminOperationResponse, error)
	UpdateProxyStatus(context.Context, *AdminUpdateProxyStatusRequest) (*AdminOperationResponse, error)
	DeleteProxy(context.Context, *AdminDeleteRequest) (*AdminOperationResponse, error)
	ListCookies(context.Context, *AdminListCookiesRequest) (*AdminListCookiesResponse, error)
	CreateCookie(context.Context, *AdminCreateCookieRequest) (*AdminCreateResourceResponse, error)
	UpdateCookie(context.Context, *AdminUpdateCookieRequest) (*AdminOperationResponse, error)
	DeleteCookie(context.Context, *AdminDeleteRequest) (*AdminOperationResponse, error)
	FreezeCookie(context.Context, *AdminFreezeCookieRequest) (*AdminFreezeCookieResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) Login(context.Context, *AdminLoginRequest) (*AdminLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAdminServiceServer) Logout(context.Context, *AdminLogoutRequest) (*AdminOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAdminServiceServer) GetCurrentUser(context.Context, *AdminSessionRequest) (*AdminCurrentUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentUser not implemented")
}
func (UnimplementedAdminServiceServer) GetOverview(context.Context, *AdminEmpty) (*AdminOverviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOverview not implemented")
}
func (UnimplementedAdminServiceServer) GetRequestTrend(context.Context, *AdminRequestTrendRequest) (*AdminRequestTrendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRequestTrend not implemented")
}
func (UnimplementedAdminServiceServer) GetUserStats(context.Context, *AdminEmpty) (*AdminUserStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserStats not implemented")
}
func (UnimplementedAdminServiceServer) GetProxySourceStatus(context.Context, *AdminEmpty) (*AdminProxySourceStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProxySourceStatus not implemented")
}
func (UnimplementedAdminServiceServer) GetProxySourcePolicy(context.Context, *AdminEmpty) (*AdminProxySourcePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProxySourcePolicy not implemented")
}
func (UnimplementedAdminServiceServer) UpdateProxySourcePolicy(context.Context, *AdminUpdateProxySourcePolicyRequest) (*AdminOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProxySourcePolicy not implemented")
}
func (UnimplementedAdminServiceServer) ListProxies(context.Context, *AdminListProxiesRequest) (*AdminListProxiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProxies not implemented")
}
func (UnimplementedAdminServiceServer) CreateProxy(context.Context, *AdminCreateProxyRequest) (*AdminCreateResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProxy not implemented")
}
func (UnimplementedAdminServiceServer) UpdateProxy(context.Context, *AdminUpdateProxyRequest) (*AdminOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProxy not implemented")
}
func (UnimplementedAdminServiceServer) UpdateProxyStatus(context.Context, *AdminUpdateProxyStatusRequest) (*AdminOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProxyStatus not implemented")
}
func (UnimplementedAdminServiceServer) DeleteProxy(context.Context, *AdminDeleteRequest) (*AdminOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProxy not implemented")
}
func (UnimplementedAdminServiceServer) ListCookies(context.Context, *AdminListCookiesRequest) (*AdminListCookiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCookies not implemented")
}
func (UnimplementedAdminServiceServer) CreateCookie(context.Context, *AdminCreateCookieRequest) (*AdminCreateResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCookie not implemented")
}
func (UnimplementedAdminServiceServer) UpdateCookie(context.Context, *AdminUpdateCookieRequest) (*AdminOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCookie not implemented")
}
func (UnimplementedAdminServiceServer) DeleteCookie(context.Context, *AdminDeleteRequest) (*AdminOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCookie not implemented")
}
func (UnimplementedAdminServiceServer) FreezeCookie(context.Context, *AdminFreezeCookieRequest) (*AdminFreezeCookieResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FreezeCookie not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Login(ctx, req.(*AdminLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminLogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Logout(ctx, req.(*AdminLogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetCurrentUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetCurrentUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetCurrentUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetCurrentUser(ctx, req.(*AdminSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetOverview(ctx, req.(*AdminEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetRequestTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRequestTrendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetRequestTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetRequestTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetRequestTrend(ctx, req.(*AdminRequestTrendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetUserStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetUserStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetUserStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetUserStats(ctx, req.(*AdminEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetProxySourceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetProxySourceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetProxySourceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetProxySourceStatus(ctx, req.(*AdminEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetProxySourcePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetProxySourcePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetProxySourcePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetProxySourcePolicy(ctx, req.(*AdminEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpdateProxySourcePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpdateProxySourcePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpdateProxySourcePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_UpdateProxySourcePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpdateProxySourcePolicy(ctx, req.(*AdminUpdateProxySourcePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListProxies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListProxiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListProxies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListProxies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListProxies(ctx, req.(*AdminListProxiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CreateProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminCreateProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreateProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_CreateProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreateProxy(ctx, req.(*AdminCreateProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpdateProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpdateProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpdateProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_UpdateProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpdateProxy(ctx, req.(*AdminUpdateProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpdateProxyStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpdateProxyStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpdateProxyStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_UpdateProxyStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpdateProxyStatus(ctx, req.(*AdminUpdateProxyStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeleteProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeleteProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeleteProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeleteProxy(ctx, req.(*AdminDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListCookies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListCookiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListCookies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListCookies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListCookies(ctx, req.(*AdminListCookiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CreateCookie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminCreateCookieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreateCookie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_CreateCookie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreateCookie(ctx, req.(*AdminCreateCookieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpdateCookie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpdateCookieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpdateCookie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_UpdateCookie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpdateCookie(ctx, req.(*AdminUpdateCookieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeleteCookie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeleteCookie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeleteCookie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeleteCookie(ctx, req.(*AdminDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_FreezeCookie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminFreezeCookieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).FreezeCookie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_FreezeCookie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).FreezeCookie(ctx, req.(*AdminFreezeCookieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AdminService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AdminService_Logout_Handler,
		},
		{
			MethodName: "GetCurrentUser",
			Handler:    _AdminService_GetCurrentUser_Handler,
		},
		{
			MethodName: "GetOverview",
			Handler:    _AdminService_GetOverview_Handler,
		},
		{
			MethodName: "GetRequestTrend",
			Handler:    _AdminService_GetRequestTrend_Handler,
		},
		{
			MethodName: "GetUserStats",
			Handler:    _AdminService_GetUserStats_Handler,
		},
		{
			MethodName: "GetProxySourceStatus",
			Handler:    _AdminService_GetProxySourceStatus_Handler,
		},
		{
			MethodName: "GetProxySourcePolicy",
			Handler:    _AdminService_GetProxySourcePolicy_Handler,
		},
		{
			MethodName: "UpdateProxySourcePolicy",
			Handler:    _AdminService_UpdateProxySourcePolicy_Handler,
		},
		{
			MethodName: "ListProxies",
			Handler:    _AdminService_ListProxies_Handler,
		},
		{
			MethodName: "CreateProxy",
			Handler:    _AdminService_CreateProxy_Handler,
		},
		{
			MethodName: "UpdateProxy",
			Handler:    _AdminService_UpdateProxy_Handler,
		},
		{
			MethodName: "UpdateProxyStatus",
			Handler:    _AdminService_UpdateProxyStatus_Handler,
		},
		{
			MethodName: "DeleteProxy",
			Handler:    _AdminService_DeleteProxy_Handler,
		},
		{
			MethodName: "ListCookies",
			Handler:    _AdminService_ListCookies_Handler,
		},
		{
			MethodName: "CreateCookie",
			Handler:    _AdminService_CreateCookie_Handler,
		},
		{
			MethodName: "UpdateCookie",
			Handler:    _AdminService_UpdateCookie_Handler,
		},
		{
			MethodName: "DeleteCookie",
			Handler:    _AdminService_DeleteCookie_Handler,
		},
		{
			MethodName: "FreezeCookie",
			Handler:    _AdminService_FreezeCookie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/admin.proto",
}
