// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/asset.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取历史请求
type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`                       // 可选:状态过滤 (0=不过滤)
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`                    // 可选:平台过滤
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // 可选:YYYY-MM-DD
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // 可选:YYYY-MM-DD
	Page          int32                  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string                 `protobuf:"bytes,8,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`          // created_at, file_size
	SortOrder     string                 `protobuf:"bytes,9,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // asc, desc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_proto_asset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{0}
}

func (x *GetHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetHistoryRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetHistoryRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GetHistoryRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetHistoryRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GetHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetHistoryRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *GetHistoryRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Items         []*HistoryItem         `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_proto_asset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{1}
}

func (x *GetHistoryResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetHistoryResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetHistoryResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetHistoryResponse) GetItems() []*HistoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type HistoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HistoryId     int64                  `protobuf:"varint,1,opt,name=history_id,json=historyId,proto3" json:"history_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Mode          string                 `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`
	Quality       string                 `protobuf:"bytes,7,opt,name=quality,proto3" json:"quality,omitempty"`
	FileSize      int64                  `protobuf:"varint,8,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	FilePath      string                 `protobuf:"bytes,10,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileName      string                 `protobuf:"bytes,11,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt   string                 `protobuf:"bytes,13,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,14,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Duration      int64                  `protobuf:"varint,15,opt,name=duration,proto3" json:"duration,omitempty"`
	Author        string                 `protobuf:"bytes,16,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryItem) Reset() {
	*x = HistoryItem{}
	mi := &file_proto_asset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryItem) ProtoMessage() {}

func (x *HistoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryItem.ProtoReflect.Descriptor instead.
func (*HistoryItem) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{2}
}

func (x *HistoryItem) GetHistoryId() int64 {
	if x != nil {
		return x.HistoryId
	}
	return 0
}

func (x *HistoryItem) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *HistoryItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HistoryItem) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *HistoryItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HistoryItem) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *HistoryItem) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *HistoryItem) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *HistoryItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HistoryItem) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *HistoryItem) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *HistoryItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *HistoryItem) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *HistoryItem) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *HistoryItem) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *HistoryItem) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

// 删除历史请求
type DeleteHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HistoryId     int64                  `protobuf:"varint,1,opt,name=history_id,json=historyId,proto3" json:"history_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHistoryRequest) Reset() {
	*x = DeleteHistoryRequest{}
	mi := &file_proto_asset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHistoryRequest) ProtoMessage() {}

func (x *DeleteHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHistoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteHistoryRequest) GetHistoryId() int64 {
	if x != nil {
		return x.HistoryId
	}
	return 0
}

func (x *DeleteHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHistoryResponse) Reset() {
	*x = DeleteHistoryResponse{}
	mi := &file_proto_asset_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHistoryResponse) ProtoMessage() {}

func (x *DeleteHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHistoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteHistoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 检查配额请求
type CheckQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckQuotaRequest) Reset() {
	*x = CheckQuotaRequest{}
	mi := &file_proto_asset_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckQuotaRequest) ProtoMessage() {}

func (x *CheckQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckQuotaRequest.ProtoReflect.Descriptor instead.
func (*CheckQuotaRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{5}
}

func (x *CheckQuotaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CheckQuotaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DailyLimit    int32                  `protobuf:"varint,1,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	DailyUsed     int32                  `protobuf:"varint,2,opt,name=daily_used,json=dailyUsed,proto3" json:"daily_used,omitempty"`
	Remaining     int32                  `protobuf:"varint,3,opt,name=remaining,proto3" json:"remaining,omitempty"`
	ResetAt       string                 `protobuf:"bytes,4,opt,name=reset_at,json=resetAt,proto3" json:"reset_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckQuotaResponse) Reset() {
	*x = CheckQuotaResponse{}
	mi := &file_proto_asset_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckQuotaResponse) ProtoMessage() {}

func (x *CheckQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckQuotaResponse.ProtoReflect.Descriptor instead.
func (*CheckQuotaResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{6}
}

func (x *CheckQuotaResponse) GetDailyLimit() int32 {
	if x != nil {
		return x.DailyLimit
	}
	return 0
}

func (x *CheckQuotaResponse) GetDailyUsed() int32 {
	if x != nil {
		return x.DailyUsed
	}
	return 0
}

func (x *CheckQuotaResponse) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *CheckQuotaResponse) GetResetAt() string {
	if x != nil {
		return x.ResetAt
	}
	return ""
}

// 消费配额请求
type ConsumeQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeQuotaRequest) Reset() {
	*x = ConsumeQuotaRequest{}
	mi := &file_proto_asset_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeQuotaRequest) ProtoMessage() {}

func (x *ConsumeQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeQuotaRequest.ProtoReflect.Descriptor instead.
func (*ConsumeQuotaRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{7}
}

func (x *ConsumeQuotaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ConsumeQuotaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Remaining     int32                  `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeQuotaResponse) Reset() {
	*x = ConsumeQuotaResponse{}
	mi := &file_proto_asset_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeQuotaResponse) ProtoMessage() {}

func (x *ConsumeQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeQuotaResponse.ProtoReflect.Descriptor instead.
func (*ConsumeQuotaResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{8}
}

func (x *ConsumeQuotaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConsumeQuotaResponse) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

// 获取统计请求
type GetUserStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatsRequest) Reset() {
	*x = GetUserStatsRequest{}
	mi := &file_proto_asset_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsRequest) ProtoMessage() {}

func (x *GetUserStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUserStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalDownloads   int64                  `protobuf:"varint,1,opt,name=total_downloads,json=totalDownloads,proto3" json:"total_downloads,omitempty"`
	SuccessDownloads int64                  `protobuf:"varint,2,opt,name=success_downloads,json=successDownloads,proto3" json:"success_downloads,omitempty"`
	FailedDownloads  int64                  `protobuf:"varint,3,opt,name=failed_downloads,json=failedDownloads,proto3" json:"failed_downloads,omitempty"`
	TotalSizeBytes   int64                  `protobuf:"varint,4,opt,name=total_size_bytes,json=totalSizeBytes,proto3" json:"total_size_bytes,omitempty"`
	TopPlatforms     []*PlatformStat        `protobuf:"bytes,5,rep,name=top_platforms,json=topPlatforms,proto3" json:"top_platforms,omitempty"`
	RecentActivity   []*DailyActivity       `protobuf:"bytes,6,rep,name=recent_activity,json=recentActivity,proto3" json:"recent_activity,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetUserStatsResponse) Reset() {
	*x = GetUserStatsResponse{}
	mi := &file_proto_asset_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsResponse) ProtoMessage() {}

func (x *GetUserStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsResponse.ProtoReflect.Descriptor instead.
func (*GetUserStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserStatsResponse) GetTotalDownloads() int64 {
	if x != nil {
		return x.TotalDownloads
	}
	return 0
}

func (x *GetUserStatsResponse) GetSuccessDownloads() int64 {
	if x != nil {
		return x.SuccessDownloads
	}
	return 0
}

func (x *GetUserStatsResponse) GetFailedDownloads() int64 {
	if x != nil {
		return x.FailedDownloads
	}
	return 0
}

func (x *GetUserStatsResponse) GetTotalSizeBytes() int64 {
	if x != nil {
		return x.TotalSizeBytes
	}
	return 0
}

func (x *GetUserStatsResponse) GetTopPlatforms() []*PlatformStat {
	if x != nil {
		return x.TopPlatforms
	}
	return nil
}

func (x *GetUserStatsResponse) GetRecentActivity() []*DailyActivity {
	if x != nil {
		return x.RecentActivity
	}
	return nil
}

type PlatformStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformStat) Reset() {
	*x = PlatformStat{}
	mi := &file_proto_asset_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformStat) ProtoMessage() {}

func (x *PlatformStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformStat.ProtoReflect.Descriptor instead.
func (*PlatformStat) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{11}
}

func (x *PlatformStat) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *PlatformStat) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DailyActivity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyActivity) Reset() {
	*x = DailyActivity{}
	mi := &file_proto_asset_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyActivity) ProtoMessage() {}

func (x *DailyActivity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyActivity.ProtoReflect.Descriptor instead.
func (*DailyActivity) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{12}
}

func (x *DailyActivity) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyActivity) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 获取文件信息请求
type GetFileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HistoryId     int64                  `protobuf:"varint,1,opt,name=history_id,json=historyId,proto3" json:"history_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoRequest) Reset() {
	*x = GetFileInfoRequest{}
	mi := &file_proto_asset_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoRequest) ProtoMessage() {}

func (x *GetFileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoRequest.ProtoReflect.Descriptor instead.
func (*GetFileInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{13}
}

func (x *GetFileInfoRequest) GetHistoryId() int64 {
	if x != nil {
		return x.HistoryId
	}
	return 0
}

func (x *GetFileInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetFileInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileHash      string                 `protobuf:"bytes,4,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoResponse) Reset() {
	*x = GetFileInfoResponse{}
	mi := &file_proto_asset_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoResponse) ProtoMessage() {}

func (x *GetFileInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoResponse.ProtoReflect.Descriptor instead.
func (*GetFileInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{14}
}

func (x *GetFileInfoResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *GetFileInfoResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GetFileInfoResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *GetFileInfoResponse) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

// 创建历史请求
type CreateHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Mode          string                 `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`
	Quality       string                 `protobuf:"bytes,7,opt,name=quality,proto3" json:"quality,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,8,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Duration      int64                  `protobuf:"varint,9,opt,name=duration,proto3" json:"duration,omitempty"`
	Author        string                 `protobuf:"bytes,10,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHistoryRequest) Reset() {
	*x = CreateHistoryRequest{}
	mi := &file_proto_asset_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHistoryRequest) ProtoMessage() {}

func (x *CreateHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHistoryRequest.ProtoReflect.Descriptor instead.
func (*CreateHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{15}
}

func (x *CreateHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateHistoryRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateHistoryRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateHistoryRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CreateHistoryRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateHistoryRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CreateHistoryRequest) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *CreateHistoryRequest) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *CreateHistoryRequest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CreateHistoryRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type CreateHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HistoryId     int64                  `protobuf:"varint,1,opt,name=history_id,json=historyId,proto3" json:"history_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHistoryResponse) Reset() {
	*x = CreateHistoryResponse{}
	mi := &file_proto_asset_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHistoryResponse) ProtoMessage() {}

func (x *CreateHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHistoryResponse.ProtoReflect.Descriptor instead.
func (*CreateHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_proto_rawDescGZIP(), []int{16}
}

func (x *CreateHistoryResponse) GetHistoryId() int64 {
	if x != nil {
		return x.HistoryId
	}
	return 0
}

var File_proto_asset_proto protoreflect.FileDescriptor

const file_proto_asset_proto_rawDesc = "" +
	"\n" +
	"\x11proto/asset.proto\x12\x05asset\"\x83\x02\n" +
	"\x11GetHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\b \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\t \x01(\tR\tsortOrder\"\x85\x01\n" +
	"\x12GetHistoryResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12(\n" +
	"\x05items\x18\x04 \x03(\v2\x12.asset.HistoryItemR\x05items\"\xba\x03\n" +
	"\vHistoryItem\x12\x1d\n" +
	"\n" +
	"history_id\x18\x01 \x01(\x03R\thistoryId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\tR\x04mode\x12\x18\n" +
	"\aquality\x18\a \x01(\tR\aquality\x12\x1b\n" +
	"\tfile_size\x18\b \x01(\x03R\bfileSize\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x1b\n" +
	"\tfile_path\x18\n" +
	" \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_name\x18\v \x01(\tR\bfileName\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12!\n" +
	"\fcompleted_at\x18\r \x01(\tR\vcompletedAt\x12\x1c\n" +
	"\tthumbnail\x18\x0e \x01(\tR\tthumbnail\x12\x1a\n" +
	"\bduration\x18\x0f \x01(\x03R\bduration\x12\x16\n" +
	"\x06author\x18\x10 \x01(\tR\x06author\"N\n" +
	"\x14DeleteHistoryRequest\x12\x1d\n" +
	"\n" +
	"history_id\x18\x01 \x01(\x03R\thistoryId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"1\n" +
	"\x15DeleteHistoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x11CheckQuotaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x8d\x01\n" +
	"\x12CheckQuotaResponse\x12\x1f\n" +
	"\vdaily_limit\x18\x01 \x01(\x05R\n" +
	"dailyLimit\x12\x1d\n" +
	"\n" +
	"daily_used\x18\x02 \x01(\x05R\tdailyUsed\x12\x1c\n" +
	"\tremaining\x18\x03 \x01(\x05R\tremaining\x12\x19\n" +
	"\breset_at\x18\x04 \x01(\tR\aresetAt\".\n" +
	"\x13ConsumeQuotaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"N\n" +
	"\x14ConsumeQuotaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x05R\tremaining\".\n" +
	"\x13GetUserStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xba\x02\n" +
	"\x14GetUserStatsResponse\x12'\n" +
	"\x0ftotal_downloads\x18\x01 \x01(\x03R\x0etotalDownloads\x12+\n" +
	"\x11success_downloads\x18\x02 \x01(\x03R\x10successDownloads\x12)\n" +
	"\x10failed_downloads\x18\x03 \x01(\x03R\x0ffailedDownloads\x12(\n" +
	"\x10total_size_bytes\x18\x04 \x01(\x03R\x0etotalSizeBytes\x128\n" +
	"\rtop_platforms\x18\x05 \x03(\v2\x13.asset.PlatformStatR\ftopPlatforms\x12=\n" +
	"\x0frecent_activity\x18\x06 \x03(\v2\x14.asset.DailyActivityR\x0erecentActivity\"@\n" +
	"\fPlatformStat\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"9\n" +
	"\rDailyActivity\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"L\n" +
	"\x12GetFileInfoRequest\x12\x1d\n" +
	"\n" +
	"history_id\x18\x01 \x01(\x03R\thistoryId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x89\x01\n" +
	"\x13GetFileInfoResponse\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tfile_hash\x18\x04 \x01(\tR\bfileHash\"\x8c\x02\n" +
	"\x14CreateHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\tR\x04mode\x12\x18\n" +
	"\aquality\x18\a \x01(\tR\aquality\x12\x1c\n" +
	"\tthumbnail\x18\b \x01(\tR\tthumbnail\x12\x1a\n" +
	"\bduration\x18\t \x01(\x03R\bduration\x12\x16\n" +
	"\x06author\x18\n" +
	" \x01(\tR\x06author\"6\n" +
	"\x15CreateHistoryResponse\x12\x1d\n" +
	"\n" +
	"history_id\x18\x01 \x01(\x03R\thistoryId2\x84\x04\n" +
	"\fAssetService\x12A\n" +
	"\n" +
	"GetHistory\x12\x18.asset.GetHistoryRequest\x1a\x19.asset.GetHistoryResponse\x12J\n" +
	"\rDeleteHistory\x12\x1b.asset.DeleteHistoryRequest\x1a\x1c.asset.DeleteHistoryResponse\x12A\n" +
	"\n" +
	"CheckQuota\x12\x18.asset.CheckQuotaRequest\x1a\x19.asset.CheckQuotaResponse\x12G\n" +
	"\fConsumeQuota\x12\x1a.asset.ConsumeQuotaRequest\x1a\x1b.asset.ConsumeQuotaResponse\x12G\n" +
	"\fGetUserStats\x12\x1a.asset.GetUserStatsRequest\x1a\x1b.asset.GetUserStatsResponse\x12D\n" +
	"\vGetFileInfo\x12\x19.asset.GetFileInfoRequest\x1a\x1a.asset.GetFileInfoResponse\x12J\n" +
	"\rCreateHistory\x12\x1b.asset.CreateHistoryRequest\x1a\x1c.asset.CreateHistoryResponseB\x1dZ\x1bvasset/api-gateway/proto;pbb\x06proto3"

var (
	file_proto_asset_proto_rawDescOnce sync.Once
	file_proto_asset_proto_rawDescData []byte
)

func file_proto_asset_proto_rawDescGZIP() []byte {
	file_proto_asset_proto_rawDescOnce.Do(func() {
		file_proto_asset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_asset_proto_rawDesc), len(file_proto_asset_proto_rawDesc)))
	})
	return file_proto_asset_proto_rawDescData
}

var file_proto_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_asset_proto_goTypes = []any{
	(*GetHistoryRequest)(nil),     // 0: asset.GetHistoryRequest
	(*GetHistoryResponse)(nil),    // 1: asset.GetHistoryResponse
	(*HistoryItem)(nil),           // 2: asset.HistoryItem
	(*DeleteHistoryRequest)(nil),  // 3: asset.DeleteHistoryRequest
	(*DeleteHistoryResponse)(nil), // 4: asset.DeleteHistoryResponse
	(*CheckQuotaRequest)(nil),     // 5: asset.CheckQuotaRequest
	(*CheckQuotaResponse)(nil),    // 6: asset.CheckQuotaResponse
	(*ConsumeQuotaRequest)(nil),   // 7: asset.ConsumeQuotaRequest
	(*ConsumeQuotaResponse)(nil),  // 8: asset.ConsumeQuotaResponse
	(*GetUserStatsRequest)(nil),   // 9: asset.GetUserStatsRequest
	(*GetUserStatsResponse)(nil),  // 10: asset.GetUserStatsResponse
	(*PlatformStat)(nil),          // 11: asset.PlatformStat
	(*DailyActivity)(nil),         // 12: asset.DailyActivity
	(*GetFileInfoRequest)(nil),    // 13: asset.GetFileInfoRequest
	(*GetFileInfoResponse)(nil),   // 14: asset.GetFileInfoResponse
	(*CreateHistoryRequest)(nil),  // 15: asset.CreateHistoryRequest
	(*CreateHistoryResponse)(nil), // 16: asset.CreateHistoryResponse
}
var file_proto_asset_proto_depIdxs = []int32{
	2,  // 0: asset.GetHistoryResponse.items:type_name -> asset.HistoryItem
	11, // 1: asset.GetUserStatsResponse.top_platforms:type_name -> asset.PlatformStat
	12, // 2: asset.GetUserStatsResponse.recent_activity:type_name -> asset.DailyActivity
	0,  // 3: asset.AssetService.GetHistory:input_type -> asset.GetHistoryRequest
	3,  // 4: asset.AssetService.DeleteHistory:input_type -> asset.DeleteHistoryRequest
	5,  // 5: asset.AssetService.CheckQuota:input_type -> asset.CheckQuotaRequest
	7,  // 6: asset.AssetService.ConsumeQuota:input_type -> asset.ConsumeQuotaRequest
	9,  // 7: asset.AssetService.GetUserStats:input_type -> asset.GetUserStatsRequest
	13, // 8: asset.AssetService.GetFileInfo:input_type -> asset.GetFileInfoRequest
	15, // 9: asset.AssetService.CreateHistory:input_type -> asset.CreateHistoryRequest
	1,  // 10: asset.AssetService.GetHistory:output_type -> asset.GetHistoryResponse
	4,  // 11: asset.AssetService.DeleteHistory:output_type -> asset.DeleteHistoryResponse
	6,  // 12: asset.AssetService.CheckQuota:output_type -> asset.CheckQuotaResponse
	8,  // 13: asset.AssetService.ConsumeQuota:output_type -> asset.ConsumeQuotaResponse
	10, // 14: asset.AssetService.GetUserStats:output_type -> asset.GetUserStatsResponse
	14, // 15: asset.AssetService.GetFileInfo:output_type -> asset.GetFileInfoResponse
	16, // 16: asset.AssetService.CreateHistory:output_type -> asset.CreateHistoryResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_asset_proto_init() }
func file_proto_asset_proto_init() {
	if File_proto_asset_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_asset_proto_rawDesc), len(file_proto_asset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_asset_proto_goTypes,
		DependencyIndexes: file_proto_asset_proto_depIdxs,
		MessageInfos:      file_proto_asset_proto_msgTypes,
	}.Build()
	File_proto_asset_proto = out.File
	file_proto_asset_proto_goTypes = nil
	file_proto_asset_proto_depIdxs = nil
}
