// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/parser.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	SkipCache     bool                   `protobuf:"varint,2,opt,name=skip_cache,json=skipCache,proto3" json:"skip_cache,omitempty"` // 可选:跳过缓存强制重新解析
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseURLRequest) Reset() {
	*x = ParseURLRequest{}
	mi := &file_proto_parser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseURLRequest) ProtoMessage() {}

func (x *ParseURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseURLRequest.ProtoReflect.Descriptor instead.
func (*ParseURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_parser_proto_rawDescGZIP(), []int{0}
}

func (x *ParseURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ParseURLRequest) GetSkipCache() bool {
	if x != nil {
		return x.SkipCache
	}
	return false
}

type ParseURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Duration      int64                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"` // 秒
	Thumbnail     string                 `protobuf:"bytes,6,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Author        string                 `protobuf:"bytes,7,opt,name=author,proto3" json:"author,omitempty"`
	UploadDate    string                 `protobuf:"bytes,8,opt,name=upload_date,json=uploadDate,proto3" json:"upload_date,omitempty"`
	ViewCount     int64                  `protobuf:"varint,9,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	Formats       []*VideoFormat         `protobuf:"bytes,10,rep,name=formats,proto3" json:"formats,omitempty"`
	CookieId      int64                  `protobuf:"varint,11,opt,name=cookie_id,json=cookieId,proto3" json:"cookie_id,omitempty"` // parser使用的cookie ID(用于downloader复用)
	ProxyUrl      string                 `protobuf:"bytes,12,opt,name=proxy_url,json=proxyUrl,proto3" json:"proxy_url,omitempty"`  // parser使用的proxy URL(用于downloader复用)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseURLResponse) Reset() {
	*x = ParseURLResponse{}
	mi := &file_proto_parser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseURLResponse) ProtoMessage() {}

func (x *ParseURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseURLResponse.ProtoReflect.Descriptor instead.
func (*ParseURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_parser_proto_rawDescGZIP(), []int{1}
}

func (x *ParseURLResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *ParseURLResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ParseURLResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ParseURLResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ParseURLResponse) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *ParseURLResponse) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *ParseURLResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ParseURLResponse) GetUploadDate() string {
	if x != nil {
		return x.UploadDate
	}
	return ""
}

func (x *ParseURLResponse) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *ParseURLResponse) GetFormats() []*VideoFormat {
	if x != nil {
		return x.Formats
	}
	return nil
}

func (x *ParseURLResponse) GetCookieId() int64 {
	if x != nil {
		return x.CookieId
	}
	return 0
}

func (x *ParseURLResponse) GetProxyUrl() string {
	if x != nil {
		return x.ProxyUrl
	}
	return ""
}

type VideoFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormatId      string                 `protobuf:"bytes,1,opt,name=format_id,json=formatId,proto3" json:"format_id,omitempty"`
	Quality       string                 `protobuf:"bytes,2,opt,name=quality,proto3" json:"quality,omitempty"`     // 1080p, 720p, etc.
	Extension     string                 `protobuf:"bytes,3,opt,name=extension,proto3" json:"extension,omitempty"` // mp4, webm
	Filesize      int64                  `protobuf:"varint,4,opt,name=filesize,proto3" json:"filesize,omitempty"`  // 字节
	Height        int32                  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`      // 分辨率高度
	Fps           float64                `protobuf:"fixed64,6,opt,name=fps,proto3" json:"fps,omitempty"`
	VideoCodec    string                 `protobuf:"bytes,7,opt,name=video_codec,json=videoCodec,proto3" json:"video_codec,omitempty"`
	AudioCodec    string                 `protobuf:"bytes,8,opt,name=audio_codec,json=audioCodec,proto3" json:"audio_codec,omitempty"`
	Width         int32                  `protobuf:"varint,9,opt,name=width,proto3" json:"width,omitempty"` // 分辨率宽度
	Vbr           float64                `protobuf:"fixed64,10,opt,name=vbr,proto3" json:"vbr,omitempty"`   // 视频码率 kbps
	Abr           float64                `protobuf:"fixed64,11,opt,name=abr,proto3" json:"abr,omitempty"`   // 音频码率 kbps
	Asr           int32                  `protobuf:"varint,12,opt,name=asr,proto3" json:"asr,omitempty"`    // 音频采样率 Hz
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoFormat) Reset() {
	*x = VideoFormat{}
	mi := &file_proto_parser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoFormat) ProtoMessage() {}

func (x *VideoFormat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoFormat.ProtoReflect.Descriptor instead.
func (*VideoFormat) Descriptor() ([]byte, []int) {
	return file_proto_parser_proto_rawDescGZIP(), []int{2}
}

func (x *VideoFormat) GetFormatId() string {
	if x != nil {
		return x.FormatId
	}
	return ""
}

func (x *VideoFormat) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *VideoFormat) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *VideoFormat) GetFilesize() int64 {
	if x != nil {
		return x.Filesize
	}
	return 0
}

func (x *VideoFormat) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VideoFormat) GetFps() float64 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *VideoFormat) GetVideoCodec() string {
	if x != nil {
		return x.VideoCodec
	}
	return ""
}

func (x *VideoFormat) GetAudioCodec() string {
	if x != nil {
		return x.AudioCodec
	}
	return ""
}

func (x *VideoFormat) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *VideoFormat) GetVbr() float64 {
	if x != nil {
		return x.Vbr
	}
	return 0
}

func (x *VideoFormat) GetAbr() float64 {
	if x != nil {
		return x.Abr
	}
	return 0
}

func (x *VideoFormat) GetAsr() int32 {
	if x != nil {
		return x.Asr
	}
	return 0
}

type ValidateURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateURLRequest) Reset() {
	*x = ValidateURLRequest{}
	mi := &file_proto_parser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateURLRequest) ProtoMessage() {}

func (x *ValidateURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateURLRequest.ProtoReflect.Descriptor instead.
func (*ValidateURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_parser_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ValidateURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // 错误信息(如果invalid)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateURLResponse) Reset() {
	*x = ValidateURLResponse{}
	mi := &file_proto_parser_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateURLResponse) ProtoMessage() {}

func (x *ValidateURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parser_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateURLResponse.ProtoReflect.Descriptor instead.
func (*ValidateURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_parser_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateURLResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateURLResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ValidateURLResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_parser_proto protoreflect.FileDescriptor

const file_proto_parser_proto_rawDesc = "" +
	"\n" +
	"\x12proto/parser.proto\x12\x06parser\"B\n" +
	"\x0fParseURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"skip_cache\x18\x02 \x01(\bR\tskipCache\"\xfc\x02\n" +
	"\x10ParseURLResponse\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x03R\bduration\x12\x1c\n" +
	"\tthumbnail\x18\x06 \x01(\tR\tthumbnail\x12\x16\n" +
	"\x06author\x18\a \x01(\tR\x06author\x12\x1f\n" +
	"\vupload_date\x18\b \x01(\tR\n" +
	"uploadDate\x12\x1d\n" +
	"\n" +
	"view_count\x18\t \x01(\x03R\tviewCount\x12-\n" +
	"\aformats\x18\n" +
	" \x03(\v2\x13.parser.VideoFormatR\aformats\x12\x1b\n" +
	"\tcookie_id\x18\v \x01(\x03R\bcookieId\x12\x1b\n" +
	"\tproxy_url\x18\f \x01(\tR\bproxyUrl\"\xb6\x02\n" +
	"\vVideoFormat\x12\x1b\n" +
	"\tformat_id\x18\x01 \x01(\tR\bformatId\x12\x18\n" +
	"\aquality\x18\x02 \x01(\tR\aquality\x12\x1c\n" +
	"\textension\x18\x03 \x01(\tR\textension\x12\x1a\n" +
	"\bfilesize\x18\x04 \x01(\x03R\bfilesize\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x05R\x06height\x12\x10\n" +
	"\x03fps\x18\x06 \x01(\x01R\x03fps\x12\x1f\n" +
	"\vvideo_codec\x18\a \x01(\tR\n" +
	"videoCodec\x12\x1f\n" +
	"\vaudio_codec\x18\b \x01(\tR\n" +
	"audioCodec\x12\x14\n" +
	"\x05width\x18\t \x01(\x05R\x05width\x12\x10\n" +
	"\x03vbr\x18\n" +
	" \x01(\x01R\x03vbr\x12\x10\n" +
	"\x03abr\x18\v \x01(\x01R\x03abr\x12\x10\n" +
	"\x03asr\x18\f \x01(\x05R\x03asr\"&\n" +
	"\x12ValidateURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"a\n" +
	"\x13ValidateURLResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\x96\x01\n" +
	"\rParserService\x12=\n" +
	"\bParseURL\x12\x17.parser.ParseURLRequest\x1a\x18.parser.ParseURLResponse\x12F\n" +
	"\vValidateURL\x12\x1a.parser.ValidateURLRequest\x1a\x1b.parser.ValidateURLResponseB Z\x1evasset/parser-service/proto;pbb\x06proto3"

var (
	file_proto_parser_proto_rawDescOnce sync.Once
	file_proto_parser_proto_rawDescData []byte
)

func file_proto_parser_proto_rawDescGZIP() []byte {
	file_proto_parser_proto_rawDescOnce.Do(func() {
		file_proto_parser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_parser_proto_rawDesc), len(file_proto_parser_proto_rawDesc)))
	})
	return file_proto_parser_proto_rawDescData
}

var file_proto_parser_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_parser_proto_goTypes = []any{
	(*ParseURLRequest)(nil),     // 0: parser.ParseURLRequest
	(*ParseURLResponse)(nil),    // 1: parser.ParseURLResponse
	(*VideoFormat)(nil),         // 2: parser.VideoFormat
	(*ValidateURLRequest)(nil),  // 3: parser.ValidateURLRequest
	(*ValidateURLResponse)(nil), // 4: parser.ValidateURLResponse
}
var file_proto_parser_proto_depIdxs = []int32{
	2, // 0: parser.ParseURLResponse.formats:type_name -> parser.VideoFormat
	0, // 1: parser.ParserService.ParseURL:input_type -> parser.ParseURLRequest
	3, // 2: parser.ParserService.ValidateURL:input_type -> parser.ValidateURLRequest
	1, // 3: parser.ParserService.ParseURL:output_type -> parser.ParseURLResponse
	4, // 4: parser.ParserService.ValidateURL:output_type -> parser.ValidateURLResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_parser_proto_init() }
func file_proto_parser_proto_init() {
	if File_proto_parser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_parser_proto_rawDesc), len(file_proto_parser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_parser_proto_goTypes,
		DependencyIndexes: file_proto_parser_proto_depIdxs,
		MessageInfos:      file_proto_parser_proto_msgTypes,
	}.Build()
	File_proto_parser_proto = out.File
	file_proto_parser_proto_goTypes = nil
	file_proto_parser_proto_depIdxs = nil
}
